In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("C:/Users/Adith/Desktop/football_analysis/Football/Player Stats 2015-16.csv")

In [4]:
data=data.dropna(subset=['Player'])

In [5]:
data=data.fillna(0)

In [6]:
data=data.replace(to_replace='-',value=0)

In [7]:
data=pd.DataFrame(data)

In [8]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [34]:
data.to_csv('data_football_preprocessed.csv',index=False)

In [9]:
new_data=data[['League', 'Team','Player', 'Position','Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,Premier League,Leicester City,Wes Morgan,Defender,38.0,2,38.0,1,1,0,0,2,1,0,0,0,0.0,1140
2,Premier League,Leicester City,Kasper Schmeichel,Goalkeeper,38.0,0,38.0,0,0,0,0,0,0,0,0,0,0.0,1710
3,Premier League,Leicester City,Marc Albrighton,Midfielder,38.0,2,34.0,2,0,1,1,0,0,0,2,0,6.0,692
4,Premier League,Leicester City,Riyad Mahrez,Midfielder,37.0,17,36.0,5,12,2,13,1,4,4,8,0,11.0,3056
5,Premier League,Leicester City,N'Golo Kante,Midfielder,37.0,1,33.0,1,0,1,0,0,0,0,1,0,0.0,1006.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4174,Scottish Premiership,Dundee United,Rodney Sneijder,Midfielder,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4175,Scottish Premiership,Dundee United,Marc McCallum,Goalkeeper,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4176,Scottish Premiership,Dundee United,Joe McGovern,Goalkeeper,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4177,Scottish Premiership,Dundee United,Scot Lochhead,Forward,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4178,Scottish Premiership,Dundee United,Jamie Robson,Midfielder,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [10]:
new_data.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [11]:
home=new_data['Home'].astype(str).astype(int)
Away=new_data['Away'].astype(str).astype(int)
rft=new_data['Right Foot'].astype(str).astype(int)
lft=new_data['Left Foot'].astype(str).astype(int)
hdr=new_data['Header'].astype(str).astype(int)
dfk=new_data['Direct Free Kick'].astype(str).astype(int)
myc=new_data['Minutes per Yellow Cards'].astype(str).astype(float)
op=new_data['Open Play'].astype(str).astype(int)
cross=new_data['Cross'].astype(str).astype(int)
penalty=new_data['Penalty'].astype(str).astype(int)

In [12]:
new_data = new_data.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [13]:
new_data["Home"]=home
new_data['Away']=Away
new_data['Right Foot']=rft
new_data['Left Foot']=lft
new_data['Header']=hdr
new_data['Direct Free Kick']=dfk
new_data['Minutes per Yellow Cards']=myc
new_data['Open Play']=op
new_data['Cross']=cross
new_data['Penalty']=penalty

In [14]:
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,Premier League,Leicester City,Wes Morgan,Defender,38.0,2,38.0,0.0,1140.00,1,1,0,0,2,0,0,1,0
2,Premier League,Leicester City,Kasper Schmeichel,Goalkeeper,38.0,0,38.0,0.0,1710.00,0,0,0,0,0,0,0,0,0
3,Premier League,Leicester City,Marc Albrighton,Midfielder,38.0,2,34.0,6.0,692.00,2,0,1,1,0,0,2,0,0
4,Premier League,Leicester City,Riyad Mahrez,Midfielder,37.0,17,36.0,11.0,3056.00,5,12,2,13,1,0,8,4,4
5,Premier League,Leicester City,N'Golo Kante,Midfielder,37.0,1,33.0,0.0,1006.67,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4174,Scottish Premiership,Dundee United,Rodney Sneijder,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4175,Scottish Premiership,Dundee United,Marc McCallum,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4176,Scottish Premiership,Dundee United,Joe McGovern,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4177,Scottish Premiership,Dundee United,Scot Lochhead,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4178,Scottish Premiership,Dundee United,Jamie Robson,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [15]:
new_data.isnull().sum()

League                      0
Team                        0
Player                      0
Position                    0
Appearances                 0
Goals                       0
Started                     0
Assists                     0
Minutes per Yellow Cards    0
Home                        0
Away                        0
Right Foot                  0
Left Foot                   0
Header                      0
Direct Free Kick            0
Open Play                   0
Cross                       0
Penalty                     0
dtype: int64

In [16]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [17]:
###Premier League##

In [18]:
data1=data[data['League']=='Premier League']
data1

,League,Team,Season,KEY,Player,Position,Appearances,Goals,Started,Started As A Sub,...,Minutes per Yellow Cards,Sent Off,Straight Red Card,Two Yellow Cards,Red - First Half,Red - Second Half,Red - Home,Red - Away,Red - Minutes Played,Minutes per Red Cards
1,Premier League,Leicester City,2015/16,Premier League|Leicester City|2015/16,Wes Morgan,Defender,38.0,2,38.0,0.0,...,1140,0.0,0,0,0,0,0,0,0.0,0.0
2,Premier League,Leicester City,2015/16,Premier League|Leicester City|2015/16,Kasper Schmeichel,Goalkeeper,38.0,0,38.0,0.0,...,1710,0.0,0,0,0,0,0,0,0.0,0.0
3,Premier League,Leicester City,2015/16,Premier League|Leicester City|2015/16,Marc Albrighton,Midfielder,38.0,2,34.0,4.0,...,692,0.0,0,0,0,0,0,0,0.0,0.0
4,Premier League,Leicester City,2015/16,Premier League|Leicester City|2015/16,Riyad Mahrez,Midfielder,37.0,17,36.0,2.0,...,3056,0.0,0,0,0,0,0,0,0.0,0.0
5,Premier League,Leicester City,2015/16,Premier League|Leicester City|2015/16,N'Golo Kante,Midfielder,37.0,1,33.0,4.0,...,1006.67,0.0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,Premier League,Aston Villa,2015/16,Premier League|Aston Villa|2015/16,Joe Cole,Midfielder,0.0,0,0.0,3.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
660,Premier League,Aston Villa,2015/16,Premier League|Aston Villa|2015/16,Keinan Davis,Forward,0.0,0,0.0,2.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
661,Premier League,Aston Villa,2015/16,Premier League|Aston Villa|2015/16,Niall Mason,Defender,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
662,Premier League,Aston Villa,2015/16,Premier League|Aston Villa|2015/16,Nathan Baker,Defender,0.0,0,0.0,3.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
663,Premier League,Aston Villa,2015/16,Premier League|Aston Villa|2015/16,Joe Bennett,Defender,0.0,0,0.0,8.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0

In [19]:
df1=data1[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df1

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,38.0,2,38.0,1,1,0,0,2,1,0,0,0,0.0,1140
2,38.0,0,38.0,0,0,0,0,0,0,0,0,0,0.0,1710
3,38.0,2,34.0,2,0,1,1,0,0,0,2,0,6.0,692
4,37.0,17,36.0,5,12,2,13,1,4,4,8,0,11.0,3056
5,37.0,1,33.0,1,0,1,0,0,0,0,1,0,0.0,1006.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
660,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
661,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
662,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
663,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [20]:
df1.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [21]:
home=df1['Home'].astype(str).astype(int)
Away=df1['Away'].astype(str).astype(int)
rft=df1['Right Foot'].astype(str).astype(int)
lft=df1['Left Foot'].astype(str).astype(int)
hdr=df1['Header'].astype(str).astype(int)
dfk=df1['Direct Free Kick'].astype(str).astype(int)
myc=df1['Minutes per Yellow Cards'].astype(str).astype(float)
op=df1['Open Play'].astype(str).astype(int)
cross=df1['Cross'].astype(str).astype(int)
penalty=df1['Penalty'].astype(str).astype(int)

In [22]:
df1 = df1.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [23]:
df1["Home"]=home
df1['Away']=Away
df1['Right Foot']=rft
df1['Left Foot']=lft
df1['Header']=hdr
df1['Direct Free Kick']=dfk
df1['Minutes per Yellow Cards']=myc
df1['Open Play']=op
df1['Cross']=cross
df1['Penalty']=penalty

In [24]:
df1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,38.0,2,38.0,0.0,1140.00,1,1,0,0,2,0,0,1,0
2,38.0,0,38.0,0.0,1710.00,0,0,0,0,0,0,0,0,0
3,38.0,2,34.0,6.0,692.00,2,0,1,1,0,0,2,0,0
4,37.0,17,36.0,11.0,3056.00,5,12,2,13,1,0,8,4,4
5,37.0,1,33.0,0.0,1006.67,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
660,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
661,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
662,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
663,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [25]:
def minmax(col):
    ncol=[]
    mx=col.max()
    mn=col.min()
    for i in col:
        ncol.append((i-mn)/(mx-mn))
    return ncol

In [26]:
dfn1=df1.apply(minmax,axis=0)

In [27]:
dfn1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,1.000000,0.08,1.000000,0.000000,0.342342,0.066667,0.066667,0.000000,0.000000,0.285714,0.0,0.000000,0.125,0.000000
2,1.000000,0.00,1.000000,0.000000,0.513514,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000,0.000000
3,1.000000,0.08,0.894737,0.315789,0.207808,0.133333,0.000000,0.052632,0.076923,0.000000,0.0,0.133333,0.000,0.000000
4,0.973684,0.68,0.947368,0.578947,0.917718,0.333333,0.800000,0.105263,1.000000,0.142857,0.0,0.533333,0.500,0.666667
5,0.973684,0.04,0.868421,0.000000,0.302303,0.066667,0.000000,0.052632,0.000000,0.000000,0.0,0.066667,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000,0.000000
660,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000,0.000000
661,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000,0.000000
662,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000,0.000000
663,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000,0.000000

In [28]:
dfn_sum1=dfn1.sum(axis=1).sort_values(ascending=False)
dfn_sum1

89     8.838005
6      8.735124
57     8.479875
4      8.179171
329    7.768322
         ...
113    0.000000
114    0.000000
115    0.000000
116    0.000000
663    0.000000
Length: 644, dtype: float64

In [30]:
data1['Player'][89]

'Sergio Aguero'

In [32]:
data['Player'][6]

'Jamie Vardy'

In [31]:
data['Player'][89]

'Sergio Aguero'

In [36]:
#####Bundesliga#######

In [35]:
data2=new_data[new_data['League']=='Bundesliga']
data2

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
665,Bundesliga,Bayern Munich,Jan Kirchhoff,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
666,Bundesliga,Bayern Munich,Manuel Neuer,Goalkeeper,34.0,0,34.0,0.0,0.0,0,0,0,0,0,0,0,0,0
667,Bundesliga,Bayern Munich,Robert Lewandowski,Forward,32.0,30,29.0,0.0,1326.5,19,11,22,5,3,0,22,4,2
668,Bundesliga,Bayern Munich,Thomas Muller,Forward,31.0,20,26.0,5.0,586.0,15,5,11,5,4,0,11,1,5
669,Bundesliga,Bayern Munich,David Alaba,Defender,30.0,1,27.0,0.0,1246.0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,Bundesliga,Hannover 96,Mike-Steven Bahre,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1214,Bundesliga,Hannover 96,Tim Dierssen,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1215,Bundesliga,Hannover 96,Phillipp Tschauner,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1216,Bundesliga,Hannover 96,Niklas Feierabend,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1217,Bundesliga,Hannover 96,Maurice Hirsch,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [37]:
data2.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Assists                     float64
Minutes per Yellow Cards    float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Direct Free Kick              int32
Open Play                     int32
Cross                         int32
Penalty                       int32
dtype: object

In [38]:
df2=data2[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
665,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
666,34.0,0,34.0,0,0,0,0,0,0,0,0,0,0.0,0.0
667,32.0,30,29.0,19,11,22,5,3,4,2,22,0,0.0,1326.5
668,31.0,20,26.0,15,5,11,5,4,1,5,11,0,5.0,586.0
669,30.0,1,27.0,0,1,0,1,0,0,0,0,0,0.0,1246.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1214,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1215,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1216,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1217,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [39]:
df2.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Cross                         int32
Penalty                       int32
Open Play                     int32
Direct Free Kick              int32
Assists                     float64
Minutes per Yellow Cards    float64
dtype: object

In [40]:
dfn2=df2.apply(minmax,axis=0)
dfn2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
665,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000
666,1.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000
667,0.941176,1.000000,0.852941,1.000000,1.000000,1.0,0.454545,0.500000,0.8,0.250,1.0,0.0,0.0000,0.433497
668,0.911765,0.666667,0.764706,0.789474,0.454545,0.5,0.454545,0.666667,0.2,0.625,0.5,0.0,0.3125,0.191503
669,0.882353,0.033333,0.794118,0.000000,0.090909,0.0,0.090909,0.000000,0.0,0.000,0.0,0.0,0.0000,0.407190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0.029412,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000
1214,0.029412,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000
1215,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000
1216,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000
1217,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0000,0.000000

In [41]:
dfn_sum2=dfn2.sum(axis=1).sort_values(ascending=False)
dfn_sum2

667    9.232160
698    8.617741
668    7.037372
756    6.123509
909    5.867436
         ...
874    0.000000
904    0.000000
905    0.000000
906    0.000000
665    0.000000
Length: 536, dtype: float64

In [42]:
data['Player'][667]

'Robert Lewandowski'

In [43]:
data2['Player'][667]

'Robert Lewandowski'

In [52]:
#####LA liga####

In [44]:
data3=new_data[new_data['League']=='La Liga']
data3

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1219,La Liga,Barcelona,Rafinha,Midfielder,6.0,1,3.0,0.0,0.00,1,0,1,0,0,0,1,0,0
1220,La Liga,Barcelona,Ivan Rakitic,Midfielder,36.0,7,30.0,0.0,857.33,3,4,6,1,0,0,5,0,0
1221,La Liga,Barcelona,Luis Suarez,Forward,35.0,40,35.0,16.0,525.00,23,17,30,5,5,0,25,6,3
1222,La Liga,Barcelona,Sergio Busquets,Midfielder,35.0,0,34.0,0.0,492.17,0,0,0,0,0,0,0,0,0
1223,La Liga,Barcelona,Neymar,Forward,34.0,24,34.0,13.0,509.50,16,8,12,12,0,1,17,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1837,La Liga,Levante,Lucas Orban,Defender,10.0,0,9.0,0.0,132.17,0,0,0,0,0,0,0,0,0
1838,La Liga,Levante,Angel Trujillo,Defender,8.0,0,8.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1839,La Liga,Levante,Nikos Karabelas,Defender,1.0,0,1.0,0.0,90.00,0,0,0,0,0,0,0,0,0
1840,La Liga,Levante,Dani Calvo,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1841,La Liga,Levante,Alvaro Traver,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [45]:
df3=data3[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1219,6.0,1,3.0,1,0,1,0,0,0,0,1,0,0.0,0.00
1220,36.0,7,30.0,3,4,6,1,0,0,0,5,0,0.0,857.33
1221,35.0,40,35.0,23,17,30,5,5,6,3,25,0,16.0,525.00
1222,35.0,0,34.0,0,0,0,0,0,0,0,0,0,0.0,492.17
1223,34.0,24,34.0,16,8,12,12,0,1,5,17,1,13.0,509.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1837,10.0,0,9.0,0,0,0,0,0,0,0,0,0,0.0,132.17
1838,8.0,0,8.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1839,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,90.00
1840,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1841,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [46]:
dfn3=df3.apply(minmax,axis=0)
dfn3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1219,0.157895,0.025,0.078947,0.043478,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.04,0.00,0.0000,0.000000
1220,0.947368,0.175,0.789474,0.130435,0.235294,0.200000,0.043478,0.000000,0.000000,0.000000,0.20,0.00,0.0000,0.264200
1221,0.921053,1.000,0.921053,1.000000,1.000000,1.000000,0.217391,0.555556,0.666667,0.428571,1.00,0.00,1.0000,0.161787
1222,0.921053,0.000,0.894737,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.0000,0.151670
1223,0.894737,0.600,0.894737,0.695652,0.470588,0.400000,0.521739,0.000000,0.111111,0.714286,0.68,0.25,0.8125,0.157011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1837,0.263158,0.000,0.236842,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.0000,0.040730
1838,0.210526,0.000,0.210526,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.0000,0.000000
1839,0.026316,0.000,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.0000,0.027735
1840,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.0000,0.000000
1841,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.0000,0.000000

In [47]:
dfn_sum3=dfn3.sum(axis=1).sort_values(ascending=False)
dfn_sum3

1248    9.887667
1221    9.872078
1225    8.335888
1223    7.202361
1490    6.257208
          ...
1682    0.000000
1681    0.000000
1680    0.000000
1679    0.000000
1841    0.000000
Length: 604, dtype: float64

In [51]:
data['Player'][1248]

'Cristiano Ronaldo'

In [52]:
####French Ligue 1####

In [53]:
data4=new_data[new_data['League']=='French Ligue 1']
data4

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1843,French Ligue 1,Paris Saint-Germain,Lucas Moura,Midfielder,36.0,9,26.0,0.0,776.00,5,4,6,1,2,0,7,1,1
1844,French Ligue 1,Paris Saint-Germain,Kevin Trapp,Goalkeeper,35.0,0,35.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1845,French Ligue 1,Paris Saint-Germain,Thiago Motta,Midfielder,32.0,1,26.0,0.0,391.17,1,0,0,1,0,0,0,0,0
1846,French Ligue 1,Paris Saint-Germain,Edinson Cavani,Forward,32.0,19,24.0,5.0,768.33,9,10,11,4,3,1,13,3,0
1847,French Ligue 1,Paris Saint-Germain,Zlatan Ibrahimovic,Forward,31.0,38,29.0,13.0,2553.00,22,16,27,6,4,1,22,9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,French Ligue 1,Troyes AC,Mory Kone,Defender,3.0,0,3.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2507,French Ligue 1,Troyes AC,Franck Grandel,Goalkeeper,1.0,0,1.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2508,French Ligue 1,Troyes AC,Mahamadou N'Diaye,Defender,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2509,French Ligue 1,Troyes AC,Samuel Grandsir,Forward,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2510,French Ligue 1,Troyes AC,Victor Paillon,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [54]:
df4=data4[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1843,36.0,9,26.0,5,4,6,1,2,1,1,7,0,0.0,776.00
1844,35.0,0,35.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1845,32.0,1,26.0,1,0,0,1,0,0,0,0,0,0.0,391.17
1846,32.0,19,24.0,9,10,11,4,3,3,0,13,1,5.0,768.33
1847,31.0,38,29.0,22,16,27,6,4,9,5,22,1,13.0,2553.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,3.0,0,3.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2507,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2508,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2509,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2510,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [55]:
dfn4=df4.apply(minmax,axis=0)
dfn4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1843,0.900,0.236842,0.684211,0.227273,0.250,0.222222,0.076923,0.4,0.111111,0.166667,0.318182,0.0,0.000000,0.236947
1844,0.875,0.000000,0.921053,0.000000,0.000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
1845,0.800,0.026316,0.684211,0.045455,0.000,0.000000,0.076923,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.119441
1846,0.800,0.500000,0.631579,0.409091,0.625,0.407407,0.307692,0.6,0.333333,0.000000,0.590909,0.5,0.277778,0.234605
1847,0.775,1.000000,0.763158,1.000000,1.000,1.000000,0.461538,0.8,1.000000,0.833333,1.000000,0.5,0.722222,0.779542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,0.075,0.000000,0.078947,0.000000,0.000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2507,0.025,0.000000,0.026316,0.000000,0.000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2508,0.025,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2509,0.025,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2510,0.000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000

In [56]:
dfn_sum4=dfn4.sum(axis=1).sort_values(ascending=False)
dfn_sum4

1847    11.634794
1948     6.318059
2380     6.316752
2247     6.252796
1846     6.217394
          ...
2105     0.000000
2106     0.000000
2107     0.000000
2108     0.000000
2510     0.000000
Length: 649, dtype: float64

In [57]:
data['Player'][1847]

'Zlatan Ibrahimovic'

In [58]:
####Eredivisie###

In [59]:
data5=new_data[new_data['League']=='Eredivisie']
data5

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
2512,Eredivisie,PSV Eindhoven,Marco van Ginkel,Midfielder,13.0,8,13.0,0.0,585.00,4,4,6,2,0,2,4,0,0
2513,Eredivisie,PSV Eindhoven,Jeroen Zoet,Goalkeeper,34.0,0,34.0,0.0,3060.00,0,0,0,0,0,0,0,0,0
2514,Eredivisie,PSV Eindhoven,Davy Propper,Midfielder,33.0,10,33.0,6.0,584.40,5,5,4,2,1,0,4,2,0
2515,Eredivisie,PSV Eindhoven,Luuk De Jong,Forward,33.0,26,32.0,9.0,1430.50,11,15,6,3,12,0,7,6,3
2516,Eredivisie,PSV Eindhoven,Santiago Arias,Midfielder,32.0,3,32.0,0.0,316.33,2,1,1,1,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,Eredivisie,SC Cambuur,Ron Janzen,Defender,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3050,Eredivisie,SC Cambuur,Rowdy van der Putten,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3051,Eredivisie,SC Cambuur,Andre Krul,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3052,Eredivisie,SC Cambuur,Delvechio Blackson,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3053,Eredivisie,SC Cambuur,Berend Schootstra,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [60]:
df5=data5[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2512,13.0,8,13.0,4,4,6,2,0,0,0,4,2,0.0,585.00
2513,34.0,0,34.0,0,0,0,0,0,0,0,0,0,0.0,3060.00
2514,33.0,10,33.0,5,5,4,2,1,2,0,4,0,6.0,584.40
2515,33.0,26,32.0,11,15,6,3,12,6,3,7,0,9.0,1430.50
2516,32.0,3,32.0,2,1,1,1,0,0,0,2,0,0.0,316.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3050,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3051,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3052,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3053,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [61]:
dfn5=df5.apply(minmax,axis=0)
dfn5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2512,0.382353,0.296296,0.382353,0.235294,0.266667,0.461538,0.142857,0.000000,0.000000,0.0,0.285714,0.666667,0.000000,0.191176
2513,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000
2514,0.970588,0.370370,0.970588,0.294118,0.333333,0.307692,0.142857,0.083333,0.333333,0.0,0.285714,0.000000,0.545455,0.190980
2515,0.970588,0.962963,0.941176,0.647059,1.000000,0.461538,0.214286,1.000000,1.000000,0.6,0.500000,0.000000,0.818182,0.467484
2516,0.941176,0.111111,0.941176,0.117647,0.066667,0.076923,0.071429,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,0.103376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,0.029412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
3050,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
3051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
3052,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
3053,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000

In [62]:
dfn_sum5=dfn5.sum(axis=1).sort_values(ascending=False)
dfn_sum5

2515    9.583276
2596    9.343414
2859    8.003267
2543    7.927189
2708    7.571104
          ...
2678    0.000000
2679    0.000000
2928    0.000000
2927    0.000000
3053    0.000000
Length: 525, dtype: float64

In [63]:
data['Player'][2515]

'Luuk De Jong'

In [71]:
####Serie A######

In [64]:
data6=new_data[new_data['League']=='Serie A']
data6

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
3055,Serie A,Juventus,Juan Cuadrado,Midfielder,28.0,4,16.0,5.0,854.50,3,1,3,0,1,0,1,3,0
3056,Serie A,Juventus,Kingsley Coman,Midfielder,1.0,0,1.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3057,Serie A,Juventus,Fernando Llorente,Forward,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3058,Serie A,Juventus,Mauricio Isla,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3059,Serie A,Juventus,Mario Lemina,Midfielder,10.0,2,7.0,0.0,181.75,0,2,2,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3757,Serie A,Hellas Verona,Claudio Winck,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3758,Serie A,Hellas Verona,Richard Marcone,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3759,Serie A,Hellas Verona,Nicola Guglielmelli,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3760,Serie A,Hellas Verona,Simon Laner,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3761,Serie A,Hellas Verona,Alessandro Speri,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [65]:
df6=data6[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3055,28.0,4,16.0,3,1,3,0,1,3,0,1,0,5.0,854.50
3056,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3057,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3058,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3059,10.0,2,7.0,0,2,2,0,0,1,0,1,0,0.0,181.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3757,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3758,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3759,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3760,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3761,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [66]:
dfn6=df6.apply(minmax,axis=0)
dfn6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3055,0.736842,0.111111,0.421053,0.136364,0.071429,0.130435,0.0,0.2,0.75,0.0,0.034483,0.0,0.416667,0.256607
3056,0.026316,0.000000,0.026316,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3057,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3058,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3059,0.263158,0.055556,0.184211,0.000000,0.142857,0.086957,0.0,0.0,0.25,0.0,0.034483,0.0,0.000000,0.054580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3759,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000
3761,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000

In [67]:
dfn_sum6=dfn6.sum(axis=1).sort_values(ascending=False)
dfn_sum6

3094    9.288412
3063    7.172405
3258    6.049194
3160    5.918121
3098    5.509287
          ...
3549    0.000000
3550    0.000000
3255    0.000000
3256    0.000000
3761    0.000000
Length: 688, dtype: float64

In [68]:
data['Player'][3094]

'Gonzalo Higuain'

In [80]:
####Scottish Premiership##

In [69]:
data7=new_data[new_data['League']=='Scottish Premiership']
data7

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
3763,Scottish Premiership,Celtic,Virgil van Dijk,Defender,5.0,0,5.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3764,Scottish Premiership,Celtic,Patrick Roberts,Midfielder,11.0,6,9.0,0.0,0.00,5,1,0,6,0,0,6,0,0
3765,Scottish Premiership,Celtic,Stefan Scepovic,Forward,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3766,Scottish Premiership,Celtic,Colin Kazim-Richards,Forward,11.0,1,4.0,0.0,162.33,0,1,1,0,0,0,1,0,0
3767,Scottish Premiership,Celtic,Craig Gordon,Goalkeeper,35.0,0,35.0,0.0,3150.00,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4174,Scottish Premiership,Dundee United,Rodney Sneijder,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4175,Scottish Premiership,Dundee United,Marc McCallum,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4176,Scottish Premiership,Dundee United,Joe McGovern,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4177,Scottish Premiership,Dundee United,Scot Lochhead,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4178,Scottish Premiership,Dundee United,Jamie Robson,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [70]:
df7=data7[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3763,5.0,0,5.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3764,11.0,6,9.0,5,1,0,6,0,0,0,6,0,0.0,0.00
3765,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3766,11.0,1,4.0,0,1,1,0,0,0,0,1,0,0.0,162.33
3767,35.0,0,35.0,0,0,0,0,0,0,0,0,0,0.0,3150.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4174,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4175,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4176,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4177,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4178,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [71]:
dfn7=df7.apply(minmax,axis=0)
dfn7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3763,0.131579,0.000000,0.131579,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
3764,0.289474,0.193548,0.236842,0.333333,0.0625,0.000000,0.285714,0.0,0.0,0.0,0.250000,0.0,0.0,0.000000
3765,0.026316,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
3766,0.289474,0.032258,0.105263,0.000000,0.0625,0.066667,0.000000,0.0,0.0,0.0,0.041667,0.0,0.0,0.051533
3767,0.921053,0.000000,0.921053,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4174,0.026316,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
4175,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
4176,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
4177,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
4178,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000

In [72]:
dfn_sum7=dfn7.sum(axis=1).sort_values(ascending=False)
dfn_sum7

3768    10.124403
3811     7.740587
3963     7.626396
4000     7.014059
3929     6.908092
          ...
3995     0.000000
3994     0.000000
3993     0.000000
3992     0.000000
4178     0.000000
Length: 405, dtype: float64

In [73]:
data['Player'][3768]

'Leigh Griffiths'