In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("C:/Users/Adith/Desktop/football_analysis/Football/Player Stats 2014-15.csv")

In [3]:
data=data.dropna(subset=['Player'])

In [4]:
data=data.fillna(0)

In [5]:
data=data.replace(to_replace='-',value=0)

In [6]:
data=pd.DataFrame(data)

In [32]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [33]:
new_data=data[['League', 'Team','Player', 'Position','Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,Premier League,Chelsea,Eden Hazard,Midfielder,38.0,14,38.0,9,5,6,5,3,2,3,8,0,9.0,1689.5
2,Premier League,Chelsea,John Terry,Defender,38.0,5,38.0,2,3,1,2,2,0,0,1,0,0.0,1710
3,Premier League,Chelsea,Branislav Ivanovic,Defender,38.0,4,38.0,1,3,3,1,0,0,0,3,0,0.0,310.91
4,Premier League,Chelsea,Nemanja Matic,Midfielder,36.0,1,35.0,0,1,0,1,0,0,0,1,0,0.0,312.4
5,Premier League,Chelsea,Gary Cahill,Defender,36.0,1,33.0,0,1,1,0,0,0,0,0,0,0.0,596.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,Scottish Premiership,St Mirren,Barry Cuddihy,Midfielder,3.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4091,Scottish Premiership,St Mirren,Jordan Stewart,Midfielder,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4092,Scottish Premiership,St Mirren,Mark Williams,Defender,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4093,Scottish Premiership,St Mirren,Mohammed Yaqub,Midfielder,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4094,Scottish Premiership,St Mirren,Daniel Wilks,Goalkeeper,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [39]:
new_data.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Assists                     float64
Minutes per Yellow Cards    float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Direct Free Kick              int32
Open Play                     int32
Cross                         int32
Penalty                       int32
dtype: object

In [35]:
home=new_data['Home'].astype(str).astype(int)
Away=new_data['Away'].astype(str).astype(int)
rft=new_data['Right Foot'].astype(str).astype(int)
lft=new_data['Left Foot'].astype(str).astype(int)
hdr=new_data['Header'].astype(str).astype(int)
dfk=new_data['Direct Free Kick'].astype(str).astype(int)
myc=new_data['Minutes per Yellow Cards'].astype(str).astype(float)
op=new_data['Open Play'].astype(str).astype(int)
cross=new_data['Cross'].astype(str).astype(int)
penalty=new_data['Penalty'].astype(str).astype(int)

In [36]:
new_data = new_data.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [37]:
new_data["Home"]=home
new_data['Away']=Away
new_data['Right Foot']=rft
new_data['Left Foot']=lft
new_data['Header']=hdr
new_data['Direct Free Kick']=dfk
new_data['Minutes per Yellow Cards']=myc
new_data['Open Play']=op
new_data['Cross']=cross
new_data['Penalty']=penalty

In [38]:
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,Premier League,Chelsea,Eden Hazard,Midfielder,38.0,14,38.0,9.0,1689.50,9,5,6,5,3,0,8,2,3
2,Premier League,Chelsea,John Terry,Defender,38.0,5,38.0,0.0,1710.00,2,3,1,2,2,0,1,0,0
3,Premier League,Chelsea,Branislav Ivanovic,Defender,38.0,4,38.0,0.0,310.91,1,3,3,1,0,0,3,0,0
4,Premier League,Chelsea,Nemanja Matic,Midfielder,36.0,1,35.0,0.0,312.40,0,1,0,1,0,0,1,0,0
5,Premier League,Chelsea,Gary Cahill,Defender,36.0,1,33.0,0.0,596.80,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,Scottish Premiership,St Mirren,Barry Cuddihy,Midfielder,3.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4091,Scottish Premiership,St Mirren,Jordan Stewart,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4092,Scottish Premiership,St Mirren,Mark Williams,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4093,Scottish Premiership,St Mirren,Mohammed Yaqub,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4094,Scottish Premiership,St Mirren,Daniel Wilks,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [41]:
new_data.isnull().sum()

League                      0
Team                        0
Player                      0
Position                    0
Appearances                 0
Goals                       0
Started                     0
Assists                     0
Minutes per Yellow Cards    0
Home                        0
Away                        0
Right Foot                  0
Left Foot                   0
Header                      0
Direct Free Kick            0
Open Play                   0
Cross                       0
Penalty                     0
dtype: int64

In [8]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [ ]:
###Premier League##

In [9]:
data1=data[data['League']=='Premier League']
data1

,League,Team,Season,KEY,Player,Position,Appearances,Goals,Started,Started As A Sub,...,Minutes per Yellow Cards,Sent Off,Straight Red Card,Two Yellow Cards,Red - First Half,Red - Second Half,Red - Home,Red - Away,Red - Minutes Played,Minutes per Red Cards
1,Premier League,Chelsea,2014/15,Premier League|Chelsea|2014/15,Eden Hazard,Midfielder,38.0,14,38.0,0.0,...,1689.5,0.0,0,0,0,0,0,0,0.0,0.0
2,Premier League,Chelsea,2014/15,Premier League|Chelsea|2014/15,John Terry,Defender,38.0,5,38.0,0.0,...,1710,0.0,0,0,0,0,0,0,0.0,0.0
3,Premier League,Chelsea,2014/15,Premier League|Chelsea|2014/15,Branislav Ivanovic,Defender,38.0,4,38.0,0.0,...,310.91,1.0,0,1,0,1,0,1,3420.0,3420.0
4,Premier League,Chelsea,2014/15,Premier League|Chelsea|2014/15,Nemanja Matic,Midfielder,36.0,1,35.0,1.0,...,312.4,1.0,1,0,0,1,1,0,3164.0,3164.0
5,Premier League,Chelsea,2014/15,Premier League|Chelsea|2014/15,Gary Cahill,Defender,36.0,1,33.0,5.0,...,596.8,0.0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,Premier League,Queens Park Rangers,2014/15,Premier League|Queens Park Rangers|2014/15,Brandon Comley,Midfielder,1.0,0,0.0,5.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
636,Premier League,Queens Park Rangers,2014/15,Premier League|Queens Park Rangers|2014/15,Brian Murphy,Goalkeeper,0.0,0,0.0,7.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
637,Premier League,Queens Park Rangers,2014/15,Premier League|Queens Park Rangers|2014/15,Aaron Mitchell,Midfielder,0.0,0,0.0,2.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
638,Premier League,Queens Park Rangers,2014/15,Premier League|Queens Park Rangers|2014/15,Frankie Sutherland,Midfielder,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
639,Premier League,Queens Park Rangers,2014/15,Premier League|Queens Park Rangers|2014/15,Michael Petrasso,Midfielder,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0

In [10]:
df1=data1[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df1

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,38.0,14,38.0,9,5,6,5,3,2,3,8,0,9.0,1689.5
2,38.0,5,38.0,2,3,1,2,2,0,0,1,0,0.0,1710
3,38.0,4,38.0,1,3,3,1,0,0,0,3,0,0.0,310.91
4,36.0,1,35.0,0,1,0,1,0,0,0,1,0,0.0,312.4
5,36.0,1,33.0,0,1,1,0,0,0,0,0,0,0.0,596.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
636,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
637,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
638,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
639,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [11]:
df1.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [12]:
home=df1['Home'].astype(str).astype(int)
Away=df1['Away'].astype(str).astype(int)
rft=df1['Right Foot'].astype(str).astype(int)
lft=df1['Left Foot'].astype(str).astype(int)
hdr=df1['Header'].astype(str).astype(int)
dfk=df1['Direct Free Kick'].astype(str).astype(int)
myc=df1['Minutes per Yellow Cards'].astype(str).astype(float)
op=df1['Open Play'].astype(str).astype(int)
cross=df1['Cross'].astype(str).astype(int)
penalty=df1['Penalty'].astype(str).astype(int)

In [13]:
df1 = df1.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [14]:
df1["Home"]=home
df1['Away']=Away
df1['Right Foot']=rft
df1['Left Foot']=lft
df1['Header']=hdr
df1['Direct Free Kick']=dfk
df1['Minutes per Yellow Cards']=myc
df1['Open Play']=op
df1['Cross']=cross
df1['Penalty']=penalty

In [15]:
df1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,38.0,14,38.0,9.0,1689.50,9,5,6,5,3,0,8,2,3
2,38.0,5,38.0,0.0,1710.00,2,3,1,2,2,0,1,0,0
3,38.0,4,38.0,0.0,310.91,1,3,3,1,0,0,3,0,0
4,36.0,1,35.0,0.0,312.40,0,1,0,1,0,0,1,0,0
5,36.0,1,33.0,0.0,596.80,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
636,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
637,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
638,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
639,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [16]:
def minmax(col):
    ncol=[]
    mx=col.max()
    mn=col.min()
    for i in col:
        ncol.append((i-mn)/(mx-mn))
    return ncol

In [17]:
dfn1=df1.apply(minmax,axis=0)

In [18]:
dfn1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,1.000000,0.538462,1.000000,0.5,0.494006,0.692308,0.384615,0.333333,0.454545,0.6,0.0,0.444444,0.285714,0.5
2,1.000000,0.192308,1.000000,0.0,0.500000,0.153846,0.230769,0.055556,0.181818,0.4,0.0,0.055556,0.000000,0.0
3,1.000000,0.153846,1.000000,0.0,0.090909,0.076923,0.230769,0.166667,0.090909,0.0,0.0,0.166667,0.000000,0.0
4,0.947368,0.038462,0.921053,0.0,0.091345,0.000000,0.076923,0.000000,0.090909,0.0,0.0,0.055556,0.000000,0.0
5,0.947368,0.038462,0.868421,0.0,0.174503,0.000000,0.076923,0.055556,0.000000,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,0.026316,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
636,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
637,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
638,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0
639,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0

In [20]:
dfn_sum1=dfn1.sum(axis=1).sort_values(ascending=False)
dfn_sum1

36     9.386280
132    8.047077
608    7.431114
1      7.227428
61     7.206377
         ...
225    0.000000
224    0.000000
223    0.000000
222    0.000000
319    0.000000
Length: 620, dtype: float64

In [21]:
data1['Player'][36]

'Sergio Aguero'

In [49]:
data['Player'][36]

'Sergio Aguero'

In [ ]:
#####Bundesliga#######

In [42]:
data2=new_data[new_data['League']=='Bundesliga']
data2

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
641,Bundesliga,Bayern Munich,Manuel Neuer,Goalkeeper,32.0,0,31.0,0.0,2866.0,0,0,0,0,0,0,0,0,0
642,Bundesliga,Bayern Munich,Mario Gotze,Midfielder,32.0,9,28.0,0.0,2249.0,8,1,9,0,0,0,8,0,0
643,Bundesliga,Bayern Munich,Robert Lewandowski,Forward,31.0,17,28.0,5.0,0.0,10,7,11,1,4,0,16,0,1
644,Bundesliga,Bayern Munich,Juan Bernat,Defender,31.0,1,28.0,0.0,2556.0,0,1,0,1,0,0,1,0,0
645,Bundesliga,Bayern Munich,Thomas Muller,Forward,31.0,13,27.0,9.0,2283.0,7,6,10,1,2,0,9,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1174,Bundesliga,SC Paderborn 07,Idir Ouali,Midfielder,6.0,0,4.0,0.0,298.0,0,0,0,0,0,0,0,0,0
1175,Bundesliga,SC Paderborn 07,Mirnes Pepic,Midfielder,2.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1176,Bundesliga,SC Paderborn 07,Thomas Bertels,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1177,Bundesliga,SC Paderborn 07,Daniel Luck,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1178,Bundesliga,SC Paderborn 07,Alexander Nuebel,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [43]:
data2.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Assists                     float64
Minutes per Yellow Cards    float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Direct Free Kick              int32
Open Play                     int32
Cross                         int32
Penalty                       int32
dtype: object

In [44]:
df2=data2[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
641,32.0,0,31.0,0,0,0,0,0,0,0,0,0,0.0,2866.0
642,32.0,9,28.0,8,1,9,0,0,0,0,8,0,0.0,2249.0
643,31.0,17,28.0,10,7,11,1,4,0,1,16,0,5.0,0.0
644,31.0,1,28.0,0,1,0,1,0,0,0,1,0,0.0,2556.0
645,31.0,13,27.0,7,6,10,1,2,1,3,9,0,9.0,2283.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1174,6.0,0,4.0,0,0,0,0,0,0,0,0,0,0.0,298.0
1175,2.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1176,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1177,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1178,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [45]:
df2.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Cross                         int32
Penalty                       int32
Open Play                     int32
Direct Free Kick              int32
Assists                     float64
Minutes per Yellow Cards    float64
dtype: object

In [47]:
dfn2=df2.apply(minmax,axis=0)
dfn2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
641,0.914286,0.000000,0.911765,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.00,0.936601
642,0.914286,0.473684,0.823529,0.666667,0.111111,0.600000,0.000000,0.0,0.0,0.000000,0.5000,0.0,0.00,0.734967
643,0.885714,0.894737,0.823529,0.833333,0.777778,0.733333,0.083333,1.0,0.0,0.166667,1.0000,0.0,0.25,0.000000
644,0.885714,0.052632,0.823529,0.000000,0.111111,0.000000,0.083333,0.0,0.0,0.000000,0.0625,0.0,0.00,0.835294
645,0.885714,0.684211,0.794118,0.583333,0.666667,0.666667,0.083333,0.5,0.2,0.500000,0.5625,0.0,0.45,0.746078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1174,0.171429,0.000000,0.117647,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.00,0.097386
1175,0.057143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.00,0.000000
1176,0.028571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.00,0.000000
1177,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.00,0.000000
1178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.00,0.000000

In [48]:
dfn_sum2=dfn2.sum(axis=1).sort_values(ascending=False)
dfn_sum2

884     8.047351
817     7.508900
643     7.448425
645     7.322621
688     7.300439
          ...
725     0.000000
1177    0.000000
904     0.000000
876     0.000000
1178    0.000000
Length: 521, dtype: float64

In [50]:
data['Player'][884]

'Alexander Meier'

In [51]:
data2['Player'][884]

'Alexander Meier'

In [52]:
#####LA liga####

In [53]:
data3=new_data[new_data['League']=='La Liga']
data3

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1180,La Liga,Barcelona,Rafinha,Midfielder,24.0,1,13.0,0.0,579.00,1,0,0,1,0,0,1,0,0
1181,La Liga,Barcelona,Lionel Messi,Forward,38.0,43,37.0,19.0,843.50,27,16,12,26,5,2,31,3,5
1182,La Liga,Barcelona,Claudio Bravo,Goalkeeper,37.0,0,37.0,0.0,3330.00,0,0,0,0,0,0,0,0,0
1183,La Liga,Barcelona,Neymar,Forward,34.0,22,30.0,7.0,443.50,12,10,18,2,2,1,17,2,1
1184,La Liga,Barcelona,Pedro Rodriguez,Midfielder,34.0,6,14.0,6.0,479.67,3,3,5,1,0,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779,La Liga,Cordoba,Fran Serrano,Defender,1.0,0,1.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1780,La Liga,Cordoba,Ion Echaide,Defender,1.0,0,1.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1781,La Liga,Cordoba,Jonathan Bijimine,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1782,La Liga,Cordoba,Jose Carlos Fernandez,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1783,La Liga,Cordoba,Jose Fran,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [54]:
df3=data3[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1180,24.0,1,13.0,1,0,0,1,0,0,0,1,0,0.0,579.00
1181,38.0,43,37.0,27,16,12,26,5,3,5,31,2,19.0,843.50
1182,37.0,0,37.0,0,0,0,0,0,0,0,0,0,0.0,3330.00
1183,34.0,22,30.0,12,10,18,2,2,2,1,17,1,7.0,443.50
1184,34.0,6,14.0,3,3,5,1,0,0,0,6,0,6.0,479.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1780,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1781,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1782,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1783,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [55]:
dfn3=df3.apply(minmax,axis=0)
dfn3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1180,0.631579,0.020833,0.342105,0.037037,0.000000,0.000000,0.038462,0.000000,0.0,0.0,0.032258,0.0,0.000000,0.172836
1181,1.000000,0.895833,0.973684,1.000000,0.695652,0.413793,1.000000,0.416667,0.3,0.5,1.000000,1.0,1.000000,0.251791
1182,0.973684,0.000000,0.973684,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.994030
1183,0.894737,0.458333,0.789474,0.444444,0.434783,0.620690,0.076923,0.166667,0.2,0.1,0.548387,0.5,0.368421,0.132388
1184,0.894737,0.125000,0.368421,0.111111,0.130435,0.172414,0.038462,0.000000,0.0,0.0,0.193548,0.0,0.315789,0.143185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779,0.026316,0.000000,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000
1780,0.026316,0.000000,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000
1781,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000
1782,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000
1783,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000

In [56]:
dfn_sum3=dfn3.sum(axis=1).sort_values(ascending=False)
dfn_sum3

1210    11.800114
1181    10.447421
1183     5.735247
1239     5.138417
1469     5.105637
          ...
1745     0.000000
1349     0.000000
1350     0.000000
1352     0.000000
1351     0.000000
Length: 585, dtype: float64

In [57]:
data['Player'][1210]

'Cristiano Ronaldo'

In [58]:
####French Ligue 1####

In [60]:
data4=new_data[new_data['League']=='French Ligue 1']
data4

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1785,French Ligue 1,Paris Saint-Germain,Edinson Cavani,Forward,35.0,17,30.0,0.0,876.67,13,4,9,6,2,0,9,2,3
1786,French Ligue 1,Paris Saint-Germain,Salvatore Sirigu,Goalkeeper,34.0,0,34.0,0.0,1501.50,0,0,0,0,0,0,0,0,0
1787,French Ligue 1,Paris Saint-Germain,Javier Pastore,Midfielder,34.0,5,31.0,12.0,687.50,2,3,5,0,0,0,5,0,0
1788,French Ligue 1,Paris Saint-Germain,Blaise Matuidi,Midfielder,34.0,4,25.0,0.0,1094.50,1,3,2,2,0,0,3,0,0
1789,French Ligue 1,Paris Saint-Germain,Marco Verratti,Midfielder,32.0,2,28.0,8.0,223.64,2,0,2,0,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,French Ligue 1,FC Metz,Janis Ikaunieks,Midfielder,4.0,0,2.0,0.0,163.00,0,0,0,0,0,0,0,0,0
2420,French Ligue 1,FC Metz,Romain Rocchi,Midfielder,3.0,0,3.0,0.0,252.00,0,0,0,0,0,0,0,0,0
2421,French Ligue 1,FC Metz,David Oberhauser,Goalkeeper,3.0,0,1.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2422,French Ligue 1,FC Metz,Moussa Gueye,Forward,3.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2423,French Ligue 1,FC Metz,Mayoro N'Doye,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [61]:
df4=data4[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1785,35.0,17,30.0,13,4,9,6,2,2,3,9,0,0.0,876.67
1786,34.0,0,34.0,0,0,0,0,0,0,0,0,0,0.0,1501.50
1787,34.0,5,31.0,2,3,5,0,0,0,0,5,0,12.0,687.50
1788,34.0,4,25.0,1,3,2,2,0,0,0,3,0,0.0,1094.50
1789,32.0,2,28.0,2,0,2,0,0,0,0,2,0,8.0,223.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,4.0,0,2.0,0,0,0,0,0,0,0,0,0,0.0,163.00
2420,3.0,0,3.0,0,0,0,0,0,0,0,0,0,0.0,252.00
2421,3.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2422,3.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2423,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [62]:
dfn4=df4.apply(minmax,axis=0)
dfn4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1785,0.921053,0.607143,0.789474,0.866667,0.307692,0.375000,0.6,0.285714,0.4,0.375,0.642857,0.0,0.000000,0.256336
1786,0.894737,0.000000,0.894737,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000,0.000000,0.0,0.000000,0.439035
1787,0.894737,0.178571,0.815789,0.133333,0.230769,0.208333,0.0,0.000000,0.0,0.000,0.357143,0.0,0.705882,0.201023
1788,0.894737,0.142857,0.657895,0.066667,0.230769,0.083333,0.2,0.000000,0.0,0.000,0.214286,0.0,0.000000,0.320029
1789,0.842105,0.071429,0.736842,0.133333,0.000000,0.083333,0.0,0.000000,0.0,0.000,0.142857,0.0,0.470588,0.065392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,0.105263,0.000000,0.052632,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000,0.000000,0.0,0.000000,0.047661
2420,0.078947,0.000000,0.078947,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000,0.000000,0.0,0.000000,0.073684
2421,0.078947,0.000000,0.026316,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000,0.000000,0.0,0.000000,0.000000
2422,0.078947,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000,0.000000,0.0,0.000000,0.000000
2423,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000,0.000000,0.0,0.000000,0.000000

In [63]:
dfn_sum4=dfn4.sum(axis=1).sort_values(ascending=False)
dfn_sum4

1819    9.173306
2068    7.996795
1873    7.988351
1798    7.297737
1785    6.426936
          ...
2002    0.000000
2001    0.000000
2000    0.000000
2390    0.000000
2066    0.000000
Length: 620, dtype: float64

In [64]:
data['Player'][1819]

'Alexandre Lacazette'

In [65]:
####Eredivisie###

In [66]:
data5=new_data[new_data['League']=='Eredivisie']
data5

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
2425,Eredivisie,PSV Eindhoven,Georginio Wijnaldum,Midfielder,33.0,14,32.0,0.0,0.0,5,9,3,0,1,0,2,2,0
2426,Eredivisie,PSV Eindhoven,Jeroen Zoet,Goalkeeper,32.0,0,32.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2427,Eredivisie,PSV Eindhoven,Jeffrey Bruma,Defender,32.0,3,30.0,0.0,2733.0,2,1,0,0,1,0,0,0,0
2428,Eredivisie,PSV Eindhoven,Luuk De Jong,Forward,31.0,20,31.0,3.0,0.0,11,9,1,2,2,0,3,1,2
2429,Eredivisie,PSV Eindhoven,Luciano Narsingh,Forward,31.0,6,30.0,3.0,2462.0,4,2,2,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,Eredivisie,FC Dordrecht,Javier Vet,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2962,Eredivisie,FC Dordrecht,Quincy Boogers,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2963,Eredivisie,FC Dordrecht,Nando Wormgoor,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2964,Eredivisie,FC Dordrecht,Sem de Wit,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2965,Eredivisie,FC Dordrecht,Brian Meulmeester,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [67]:
df5=data5[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2425,33.0,14,32.0,5,9,3,0,1,2,0,2,0,0.0,0.0
2426,32.0,0,32.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2427,32.0,3,30.0,2,1,0,0,1,0,0,0,0,0.0,2733.0
2428,31.0,20,31.0,11,9,1,2,2,1,2,3,0,3.0,0.0
2429,31.0,6,30.0,4,2,2,0,0,1,0,1,0,3.0,2462.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2962,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2963,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2964,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2965,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [68]:
dfn5=df5.apply(minmax,axis=0)
dfn5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2425,0.970588,0.636364,0.941176,0.454545,0.818182,0.75,0.0,0.5,1.0,0.0,0.50,0.0,0.0,0.000000
2426,0.941176,0.000000,0.941176,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000
2427,0.941176,0.136364,0.882353,0.181818,0.090909,0.00,0.0,0.5,0.0,0.0,0.00,0.0,0.0,0.920202
2428,0.911765,0.909091,0.911765,1.000000,0.818182,0.25,0.5,1.0,0.5,0.5,0.75,0.0,0.5,0.000000
2429,0.911765,0.272727,0.882353,0.363636,0.181818,0.50,0.0,0.0,0.5,0.0,0.25,0.0,0.5,0.828956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,0.029412,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000
2962,0.029412,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000
2963,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000
2964,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000
2965,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000

In [69]:
dfn_sum5=dfn5.sum(axis=1).sort_values(ascending=False)
dfn_sum5

2430    8.779857
2428    8.550802
2626    7.295455
2874    7.172868
2631    6.679125
          ...
2783    0.000000
2782    0.000000
2903    0.000000
2902    0.000000
2965    0.000000
Length: 524, dtype: float64

In [70]:
data['Player'][2430]

'Memphis Depay'

In [71]:
####Serie A######

In [72]:
data6=new_data[new_data['League']=='Serie A']
data6

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
2967,Serie A,Juventus,Claudio Marchisio,Midfielder,35.0,3,33.0,0.0,318.33,1,2,3,0,0,0,2,0,1
2968,Serie A,Juventus,Roberto Pereyra,Midfielder,35.0,4,27.0,0.0,1140.50,3,1,3,1,0,0,4,0,0
2969,Serie A,Juventus,Leonardo Bonucci,Defender,34.0,3,33.0,0.0,376.75,3,0,3,0,0,0,1,0,0
2970,Serie A,Juventus,Gianluigi Buffon,Goalkeeper,33.0,0,33.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2971,Serie A,Juventus,Carlos Tevez,Forward,32.0,20,29.0,7.0,431.83,14,6,16,3,1,1,15,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3680,Serie A,Parma,Solomon Nyantakyi,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3681,Serie A,Parma,Marijan Coric,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3682,Serie A,Parma,Pavol Bajza,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3683,Serie A,Parma,Riccardo Bertozzi,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3684,Serie A,Parma,Alex Cordaz,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [76]:
df6=data6[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2967,35.0,3,33.0,1,2,3,0,0,0,1,2,0,0.0,318.33
2968,35.0,4,27.0,3,1,3,1,0,0,0,4,0,0.0,1140.50
2969,34.0,3,33.0,3,0,3,0,0,0,0,1,0,0.0,376.75
2970,33.0,0,33.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2971,32.0,20,29.0,14,6,16,3,1,0,2,15,1,7.0,431.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3680,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3681,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3682,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3683,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3684,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [77]:
dfn6=df6.apply(minmax,axis=0)
dfn6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2967,0.921053,0.136364,0.868421,0.071429,0.2,0.1875,0.000000,0.0,0.0,0.125,0.133333,0.0,0.0,0.101057
2968,0.921053,0.181818,0.710526,0.214286,0.1,0.1875,0.076923,0.0,0.0,0.000,0.266667,0.0,0.0,0.362063
2969,0.894737,0.136364,0.868421,0.214286,0.0,0.1875,0.000000,0.0,0.0,0.000,0.066667,0.0,0.0,0.119603
2970,0.868421,0.000000,0.868421,0.000000,0.0,0.0000,0.000000,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000
2971,0.842105,0.909091,0.763158,1.000000,0.6,1.0000,0.230769,0.2,0.0,0.250,1.000000,0.5,0.7,0.137089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3680,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000000,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000
3681,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000000,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000
3682,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000000,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000
3683,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000000,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000
3684,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000000,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000

In [78]:
dfn_sum6=dfn6.sum(axis=1).sort_values(ascending=False)
dfn_sum6

3397    9.102927
3214    9.100997
2971    8.132212
3105    7.664785
3363    7.529019
          ...
3683    0.000000
3354    0.000000
3355    0.000000
3356    0.000000
3684    0.000000
Length: 699, dtype: float64

In [79]:
data['Player'][3397]

'Luca Toni'

In [80]:
####Scottish Premiership##

In [81]:
data7=new_data[new_data['League']=='Scottish Premiership']
data7

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
3686,Scottish Premiership,Celtic,Virgil van Dijk,Defender,35.0,4,35.0,5.0,1050.00,2,2,3,0,1,1,2,1,0
3687,Scottish Premiership,Celtic,Emilo Izaguirre,Defender,35.0,1,34.0,0.0,505.83,0,1,0,1,0,0,1,0,0
3688,Scottish Premiership,Celtic,Stefan Johansen,Forward,34.0,9,33.0,7.0,569.00,5,4,2,7,0,0,8,0,1
3689,Scottish Premiership,Celtic,Craig Gordon,Goalkeeper,33.0,0,33.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3690,Scottish Premiership,Celtic,Scott Brown,Midfielder,32.0,5,31.0,0.0,310.78,4,1,4,1,0,0,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,Scottish Premiership,St Mirren,Barry Cuddihy,Midfielder,3.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4091,Scottish Premiership,St Mirren,Jordan Stewart,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4092,Scottish Premiership,St Mirren,Mark Williams,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4093,Scottish Premiership,St Mirren,Mohammed Yaqub,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4094,Scottish Premiership,St Mirren,Daniel Wilks,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [82]:
df7=data7[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3686,35.0,4,35.0,2,2,3,0,1,1,0,2,1,5.0,1050.00
3687,35.0,1,34.0,0,1,0,1,0,0,0,1,0,0.0,505.83
3688,34.0,9,33.0,5,4,2,7,0,0,1,8,0,7.0,569.00
3689,33.0,0,33.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3690,32.0,5,31.0,4,1,4,1,0,0,0,5,0,0.0,310.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,3.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4091,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4092,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4093,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4094,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [83]:
dfn7=df7.apply(minmax,axis=0)
dfn7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3686,0.921053,0.222222,0.921053,0.222222,0.222222,0.214286,0.0,0.25,0.5,0.0,0.166667,0.5,0.5,0.414528
3687,0.921053,0.055556,0.894737,0.000000,0.111111,0.000000,0.1,0.00,0.0,0.0,0.083333,0.0,0.0,0.199696
3688,0.894737,0.500000,0.868421,0.555556,0.444444,0.142857,0.7,0.00,0.0,0.2,0.666667,0.0,0.7,0.224635
3689,0.868421,0.000000,0.868421,0.000000,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000
3690,0.842105,0.277778,0.815789,0.444444,0.111111,0.285714,0.1,0.00,0.0,0.0,0.416667,0.0,0.0,0.122692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,0.078947,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000
4091,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000
4092,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000
4093,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000
4094,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000

In [84]:
dfn_sum7=dfn7.sum(axis=1).sort_values(ascending=False)
dfn_sum7

3724    8.524416
3918    8.180397
3817    8.126311
4021    8.120518
3697    6.891699
          ...
4058    0.000000
3720    0.000000
3719    0.000000
3718    0.000000
4094    0.000000
Length: 398, dtype: float64

In [85]:
data['Player'][3724]

'Adam Rooney'