In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("C:/Users/Adith/Desktop/football_analysis/Football/Player Stats 2016-17.csv")

In [4]:
data=data.dropna(subset=['Player'])

In [5]:
data=data.fillna(0)

In [6]:
data=data.replace(to_replace='-',value=0)

In [7]:
data=pd.DataFrame(data)

In [8]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [9]:
new_data=data[['League', 'Team','Player', 'Position','Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,Premier League,Chelsea,Cesar Azpilicueta,Defender,38.0,1,38.0,1,0,1,0,0,0,0,0,0,0.0,855
2,Premier League,Chelsea,Gary Cahill,Defender,37.0,6,36.0,4,2,3,0,3,0,0,0,0,0.0,659.2
3,Premier League,Chelsea,Eden Hazard,Midfielder,36.0,16,36.0,12,4,12,4,0,0,2,14,0,0.0,1002
4,Premier League,Chelsea,Thibaut Courtois,Goalkeeper,36.0,0,36.0,0,0,0,0,0,0,0,0,0,0.0,3240
5,Premier League,Chelsea,Diego Costa,Forward,35.0,20,35.0,11,9,13,5,2,2,0,13,0,7.0,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4050,Scottish Premiership,Inverness Cali,Jason Brown,Midfielder,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4051,Scottish Premiership,Inverness Cali,Daniel Hoban,Goalkeeper,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4052,Scottish Premiership,Inverness Cali,Sam Robertson,Defender,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4053,Scottish Premiership,Inverness Cali,Andrew MacRae,Forward,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4054,Scottish Premiership,Inverness Cali,Blair MacLennan,Midfielder,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [10]:
new_data.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [11]:
home=new_data['Home'].astype(str).astype(int)
Away=new_data['Away'].astype(str).astype(int)
rft=new_data['Right Foot'].astype(str).astype(int)
lft=new_data['Left Foot'].astype(str).astype(int)
hdr=new_data['Header'].astype(str).astype(int)
dfk=new_data['Direct Free Kick'].astype(str).astype(int)
myc=new_data['Minutes per Yellow Cards'].astype(str).astype(float)
op=new_data['Open Play'].astype(str).astype(int)
cross=new_data['Cross'].astype(str).astype(int)
penalty=new_data['Penalty'].astype(str).astype(int)

In [12]:
new_data = new_data.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [13]:
new_data["Home"]=home
new_data['Away']=Away
new_data['Right Foot']=rft
new_data['Left Foot']=lft
new_data['Header']=hdr
new_data['Direct Free Kick']=dfk
new_data['Minutes per Yellow Cards']=myc
new_data['Open Play']=op
new_data['Cross']=cross
new_data['Penalty']=penalty

In [14]:
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,Premier League,Chelsea,Cesar Azpilicueta,Defender,38.0,1,38.0,0.0,855.0,1,0,1,0,0,0,0,0,0
2,Premier League,Chelsea,Gary Cahill,Defender,37.0,6,36.0,0.0,659.2,4,2,3,0,3,0,0,0,0
3,Premier League,Chelsea,Eden Hazard,Midfielder,36.0,16,36.0,0.0,1002.0,12,4,12,4,0,0,14,0,2
4,Premier League,Chelsea,Thibaut Courtois,Goalkeeper,36.0,0,36.0,0.0,3240.0,0,0,0,0,0,0,0,0,0
5,Premier League,Chelsea,Diego Costa,Forward,35.0,20,35.0,7.0,309.0,11,9,13,5,2,0,13,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4050,Scottish Premiership,Inverness Cali,Jason Brown,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4051,Scottish Premiership,Inverness Cali,Daniel Hoban,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4052,Scottish Premiership,Inverness Cali,Sam Robertson,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4053,Scottish Premiership,Inverness Cali,Andrew MacRae,Forward,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4054,Scottish Premiership,Inverness Cali,Blair MacLennan,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [15]:
new_data.isnull().sum()

League                      0
Team                        0
Player                      0
Position                    0
Appearances                 0
Goals                       0
Started                     0
Assists                     0
Minutes per Yellow Cards    0
Home                        0
Away                        0
Right Foot                  0
Left Foot                   0
Header                      0
Direct Free Kick            0
Open Play                   0
Cross                       0
Penalty                     0
dtype: int64

In [16]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [17]:
###Premier League##

In [17]:
data1=data[data['League']=='Premier League']
data1

,League,Team,Season,KEY,Player,Position,Appearances,Goals,Started,Started As A Sub,...,Minutes per Yellow Cards,Sent Off,Straight Red Card,Two Yellow Cards,Red - First Half,Red - Second Half,Red - Home,Red - Away,Red - Minutes Played,Minutes per Red Cards
1,Premier League,Chelsea,2016/17,Premier League|Chelsea|2016/17,Cesar Azpilicueta,Defender,38.0,1,38.0,0.0,...,855,0.0,0,0,0,0,0,0,0.0,0.0
2,Premier League,Chelsea,2016/17,Premier League|Chelsea|2016/17,Gary Cahill,Defender,37.0,6,36.0,2.0,...,659.2,0.0,0,0,0,0,0,0,0.0,0.0
3,Premier League,Chelsea,2016/17,Premier League|Chelsea|2016/17,Eden Hazard,Midfielder,36.0,16,36.0,0.0,...,1002,0.0,0,0,0,0,0,0,0.0,0.0
4,Premier League,Chelsea,2016/17,Premier League|Chelsea|2016/17,Thibaut Courtois,Goalkeeper,36.0,0,36.0,0.0,...,3240,0.0,0,0,0,0,0,0,0.0,0.0
5,Premier League,Chelsea,2016/17,Premier League|Chelsea|2016/17,Diego Costa,Forward,35.0,20,35.0,1.0,...,309,0.0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,Premier League,Sunderland,2016/17,Premier League|Sunderland|2016/17,Josh Maja,Forward,0.0,0,0.0,4.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
636,Premier League,Sunderland,2016/17,Premier League|Sunderland|2016/17,Mika,Goalkeeper,0.0,0,0.0,16.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
637,Premier League,Sunderland,2016/17,Premier League|Sunderland|2016/17,Maksymilian Stryjek,Goalkeeper,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
638,Premier League,Sunderland,2016/17,Premier League|Sunderland|2016/17,Tom Robson,Defender,0.0,0,0.0,2.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
639,Premier League,Sunderland,2016/17,Premier League|Sunderland|2016/17,Ethan Robson,Midfielder,0.0,0,0.0,2.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0

In [18]:
df1=data1[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df1

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,38.0,1,38.0,1,0,1,0,0,0,0,0,0,0.0,855
2,37.0,6,36.0,4,2,3,0,3,0,0,0,0,0.0,659.2
3,36.0,16,36.0,12,4,12,4,0,0,2,14,0,0.0,1002
4,36.0,0,36.0,0,0,0,0,0,0,0,0,0,0.0,3240
5,35.0,20,35.0,11,9,13,5,2,2,0,13,0,7.0,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
636,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
637,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
638,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
639,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [19]:
df1.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [20]:
home=df1['Home'].astype(str).astype(int)
Away=df1['Away'].astype(str).astype(int)
rft=df1['Right Foot'].astype(str).astype(int)
lft=df1['Left Foot'].astype(str).astype(int)
hdr=df1['Header'].astype(str).astype(int)
dfk=df1['Direct Free Kick'].astype(str).astype(int)
myc=df1['Minutes per Yellow Cards'].astype(str).astype(float)
op=df1['Open Play'].astype(str).astype(int)
cross=df1['Cross'].astype(str).astype(int)
penalty=df1['Penalty'].astype(str).astype(int)

In [21]:
df1 = df1.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [22]:
df1["Home"]=home
df1['Away']=Away
df1['Right Foot']=rft
df1['Left Foot']=lft
df1['Header']=hdr
df1['Direct Free Kick']=dfk
df1['Minutes per Yellow Cards']=myc
df1['Open Play']=op
df1['Cross']=cross
df1['Penalty']=penalty

In [23]:
df1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,38.0,1,38.0,0.0,855.0,1,0,1,0,0,0,0,0,0
2,37.0,6,36.0,0.0,659.2,4,2,3,0,3,0,0,0,0
3,36.0,16,36.0,0.0,1002.0,12,4,12,4,0,0,14,0,2
4,36.0,0,36.0,0.0,3240.0,0,0,0,0,0,0,0,0,0
5,35.0,20,35.0,7.0,309.0,11,9,13,5,2,0,13,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
636,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
637,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
638,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
639,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [24]:
def minmax(col):
    ncol=[]
    mx=col.max()
    mn=col.min()
    for i in col:
        ncol.append((i-mn)/(mx-mn))
    return ncol

In [25]:
dfn1=df1.apply(minmax,axis=0)

In [26]:
dfn1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,1.000000,0.034483,1.000000,0.000000,0.256065,0.058824,0.000000,0.05,0.000000,0.000,0.0,0.000000,0.000000,0.000000
2,0.973684,0.206897,0.947368,0.000000,0.197424,0.235294,0.133333,0.15,0.000000,0.375,0.0,0.000000,0.000000,0.000000
3,0.947368,0.551724,0.947368,0.000000,0.300090,0.705882,0.266667,0.60,0.333333,0.000,0.0,0.823529,0.000000,0.285714
4,0.947368,0.000000,0.947368,0.000000,0.970350,0.000000,0.000000,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.000000
5,0.921053,0.689655,0.921053,0.388889,0.092543,0.647059,0.600000,0.65,0.416667,0.250,0.0,0.764706,0.285714,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.000000
636,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.000000
637,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.000000
638,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.000000
639,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000,0.0,0.000000,0.000000,0.000000

In [27]:
dfn_sum1=dfn1.sum(axis=1).sort_values(ascending=False)
dfn_sum1

180    9.442320
36     8.970880
114    8.675071
27     7.048549
5      6.627338
         ...
336    0.000000
208    0.000000
108    0.000000
109    0.000000
639    0.000000
Length: 620, dtype: float64

In [28]:
data1['Player'][180]

'Romelu Lukaku'

In [29]:
data['Player'][36]

'Harry Kane'

In [30]:
#####Bundesliga#######

In [31]:
data2=new_data[new_data['League']=='Bundesliga']
data2

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
641,Bundesliga,Bayern Munich,Robert Lewandowski,Forward,33.0,30,31.0,5.0,555.2,18,12,19,9,2,2,18,2,5
642,Bundesliga,Bayern Munich,David Alaba,Defender,32.0,4,29.0,0.0,2508.0,1,3,0,4,0,3,1,0,0
643,Bundesliga,Bayern Munich,Thomas Muller,Forward,29.0,5,25.0,12.0,0.0,3,2,2,3,0,0,4,0,0
644,Bundesliga,Bayern Munich,Thiago Alcantara,Midfielder,27.0,6,26.0,5.0,458.2,5,1,4,0,2,0,6,0,0
645,Bundesliga,Bayern Munich,Philipp Lahm,Defender,27.0,1,25.0,0.0,2180.0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1197,Bundesliga,SV Darmstadt 98,Victor Obinna,Forward,2.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1198,Bundesliga,SV Darmstadt 98,Benjamin Gorka,Defender,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1199,Bundesliga,SV Darmstadt 98,Silas Zehnder,Forward,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1200,Bundesliga,SV Darmstadt 98,Junior Diaz,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1201,Bundesliga,SV Darmstadt 98,Ihor Berezovskyi,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [32]:
data2.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Assists                     float64
Minutes per Yellow Cards    float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Direct Free Kick              int32
Open Play                     int32
Cross                         int32
Penalty                       int32
dtype: object

In [33]:
df2=data2[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
641,33.0,30,31.0,18,12,19,9,2,2,5,18,2,5.0,555.2
642,32.0,4,29.0,1,3,0,4,0,0,0,1,3,0.0,2508.0
643,29.0,5,25.0,3,2,2,3,0,0,0,4,0,12.0,0.0
644,27.0,6,26.0,5,1,4,0,2,0,0,6,0,5.0,458.2
645,27.0,1,25.0,1,0,1,0,0,0,0,1,0,0.0,2180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1197,2.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1198,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1199,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1200,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1201,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [34]:
df2.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Cross                         int32
Penalty                       int32
Open Play                     int32
Direct Free Kick              int32
Assists                     float64
Minutes per Yellow Cards    float64
dtype: object

In [35]:
dfn2=df2.apply(minmax,axis=0)
dfn2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
641,0.970588,0.967742,0.911765,1.000000,0.800000,1.000000,0.750000,0.333333,0.5,1.0,0.750000,0.50,0.277778,0.181438
642,0.941176,0.129032,0.852941,0.055556,0.200000,0.000000,0.333333,0.000000,0.0,0.0,0.041667,0.75,0.000000,0.819608
643,0.852941,0.161290,0.735294,0.166667,0.133333,0.105263,0.250000,0.000000,0.0,0.0,0.166667,0.00,0.666667,0.000000
644,0.794118,0.193548,0.764706,0.277778,0.066667,0.210526,0.000000,0.333333,0.0,0.0,0.250000,0.00,0.277778,0.149739
645,0.794118,0.032258,0.735294,0.055556,0.000000,0.052632,0.000000,0.000000,0.0,0.0,0.041667,0.00,0.000000,0.712418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1197,0.058824,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,0.000000
1198,0.029412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,0.000000
1199,0.029412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,0.000000
1200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,0.000000
1201,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,0.000000

In [36]:
dfn_sum2=dfn2.sum(axis=1).sort_values(ascending=False)
dfn_sum2

641     9.942644
699     9.506283
758     8.728476
674     7.365371
731     7.019879
          ...
1164    0.000000
1163    0.000000
1162    0.000000
1072    0.000000
1201    0.000000
Length: 544, dtype: float64

In [37]:
data['Player'][641]

'Robert Lewandowski'

In [38]:
# data2['Player'][699]

'Pierre Emerick Aubameyang'

In [39]:
#####LA liga####

In [40]:
data3=new_data[new_data['League']=='La Liga']
data3

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1203,La Liga,Real Madrid,Lucas Vazquez,Midfielder,33.0,2,12.0,8.0,346.00,0,2,0,1,0,0,1,0,0
1204,La Liga,Real Madrid,Marcelo,Defender,30.0,2,26.0,8.0,1137.50,1,1,1,1,0,0,2,0,0
1205,La Liga,Real Madrid,Cristiano Ronaldo,Forward,29.0,25,29.0,6.0,636.00,11,14,15,3,5,1,11,4,6
1206,La Liga,Real Madrid,Toni Kroos,Midfielder,29.0,4,28.0,12.0,416.83,3,1,4,0,0,0,4,0,0
1207,La Liga,Real Madrid,Nacho,Defender,29.0,2,25.0,0.0,478.40,2,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,La Liga,Granada CF,Panagiotis Kone,Midfielder,2.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1822,La Liga,Granada CF,Jean Carlos Silva,Forward,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1823,La Liga,Granada CF,Sergi Guardiola,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1824,La Liga,Granada CF,Rui Silva,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1825,La Liga,Granada CF,Oier Olazabal,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [41]:
df3=data3[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1203,33.0,2,12.0,0,2,0,1,0,0,0,1,0,8.0,346.00
1204,30.0,2,26.0,1,1,1,1,0,0,0,2,0,8.0,1137.50
1205,29.0,25,29.0,11,14,15,3,5,4,6,11,1,6.0,636.00
1206,29.0,4,28.0,3,1,4,0,0,0,0,4,0,12.0,416.83
1207,29.0,2,25.0,2,0,1,0,1,0,0,0,1,0.0,478.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,2.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1822,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1823,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1824,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1825,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [42]:
dfn3=df3.apply(minmax,axis=0)
dfn3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1203,0.868421,0.054054,0.315789,0.000000,0.142857,0.000000,0.034483,0.000000,0.0,0.0,0.04,0.000000,0.615385,0.106790
1204,0.789474,0.054054,0.684211,0.043478,0.071429,0.045455,0.034483,0.000000,0.0,0.0,0.08,0.000000,0.615385,0.351080
1205,0.763158,0.675676,0.763158,0.478261,1.000000,0.681818,0.103448,0.714286,1.0,1.0,0.44,0.333333,0.461538,0.196296
1206,0.763158,0.108108,0.736842,0.130435,0.071429,0.181818,0.000000,0.000000,0.0,0.0,0.16,0.000000,0.923077,0.128651
1207,0.763158,0.054054,0.657895,0.086957,0.000000,0.045455,0.000000,0.142857,0.0,0.0,0.00,0.333333,0.000000,0.147654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,0.052632,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.000000,0.000000
1822,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.000000,0.000000
1823,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.000000,0.000000
1824,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.000000,0.000000
1825,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.000000,0.000000

In [43]:
dfn_sum3=dfn3.sum(axis=1).sort_values(ascending=False)
dfn_sum3

1234    10.049937
1205     8.610973
1233     8.177505
1261     6.417417
1565     6.362380
          ...
1324     0.000000
1325     0.000000
1326     0.000000
1327     0.000000
1825     0.000000
Length: 604, dtype: float64

In [44]:
data['Player'][1234]

'Lionel Messi'

In [45]:
####French Ligue 1####

In [46]:
data4=new_data[new_data['League']=='French Ligue 1']
data4

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1827,French Ligue 1,AS Monaco,Adama Traore,Midfielder,5.0,2,4.0,0.0,281.00,1,1,0,2,0,0,2,0,0
1828,French Ligue 1,AS Monaco,Marcel Tisserand,Defender,1.0,0,1.0,0.0,90.00,0,0,0,0,0,0,0,0,0
1829,French Ligue 1,AS Monaco,Elderson,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1830,French Ligue 1,AS Monaco,Fabinho,Defender,37.0,9,33.0,0.0,383.75,4,5,9,0,0,0,2,0,7
1831,French Ligue 1,AS Monaco,Bernardo Silva,Midfielder,37.0,8,33.0,9.0,933.67,2,6,0,5,3,0,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2481,French Ligue 1,SC Bastia,Sami Ben Amar,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2482,French Ligue 1,SC Bastia,Hugo Magnetti,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2483,French Ligue 1,SC Bastia,Fode Camara,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2484,French Ligue 1,SC Bastia,Lucas Triki,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2485,French Ligue 1,SC Bastia,Lyes Houri,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [47]:
df4=data4[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1827,5.0,2,4.0,1,1,0,2,0,0,0,2,0,0.0,281.00
1828,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,90.00
1829,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1830,37.0,9,33.0,4,5,9,0,0,0,7,2,0,0.0,383.75
1831,37.0,8,33.0,2,6,0,5,3,3,0,4,0,9.0,933.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2481,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2482,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2483,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2484,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2485,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [48]:
dfn4=df4.apply(minmax,axis=0)
dfn4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1827,0.131579,0.057143,0.105263,0.0625,0.052632,0.000,0.166667,0.000000,0.000000,0.0,0.125,0.0,0.000000,0.082164
1828,0.026316,0.000000,0.026316,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.026316
1829,0.000000,0.000000,0.000000,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.000000
1830,0.973684,0.257143,0.868421,0.2500,0.263158,0.375,0.000000,0.000000,0.000000,0.7,0.125,0.0,0.000000,0.112208
1831,0.973684,0.228571,0.868421,0.1250,0.315789,0.000,0.416667,0.428571,0.333333,0.0,0.250,0.0,0.642857,0.273003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2481,0.000000,0.000000,0.000000,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.000000
2482,0.000000,0.000000,0.000000,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.000000
2483,0.000000,0.000000,0.000000,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.000000
2484,0.000000,0.000000,0.000000,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.000000
2485,0.000000,0.000000,0.000000,0.0000,0.000000,0.000,0.000000,0.000000,0.000000,0.0,0.000,0.0,0.000000,0.000000

In [49]:
dfn_sum4=dfn4.sum(axis=1).sort_values(ascending=False)
dfn_sum4

1861    10.206742
1930     7.615758
1840     6.773914
1957     6.337135
1960     6.262837
          ...
2120     0.000000
2121     0.000000
2122     0.000000
2149     0.000000
2155     0.000000
Length: 640, dtype: float64

In [51]:
data['Player'][1861]

'Edinson Cavani'

In [52]:
####Eredivisie###

In [53]:
data5=new_data[new_data['League']=='Eredivisie']
data5

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
2487,Eredivisie,Feyenoord,Eric Botteghin,Defender,34.0,4,34.0,0.0,1020.00,2,2,1,1,2,0,0,0,0
2488,Eredivisie,Feyenoord,Jens Toornstra,Midfielder,34.0,14,31.0,9.0,933.00,14,0,12,0,1,0,11,2,0
2489,Eredivisie,Feyenoord,Nicolai Jorgensen,Forward,33.0,21,33.0,13.0,0.00,12,9,18,2,1,0,16,3,1
2490,Eredivisie,Feyenoord,Brad Jones,Goalkeeper,32.0,0,32.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2491,Eredivisie,Feyenoord,Jan-Arie van der Heijden,Defender,31.0,3,29.0,0.0,371.29,2,1,1,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2873,Eredivisie,Go Ahead Eagles,Lars Lambooij,Midfielder,6.0,0,6.0,0.0,485.00,0,0,0,0,0,0,0,0,0
2874,Eredivisie,Go Ahead Eagles,Lum Rexhepi,Defender,2.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2875,Eredivisie,Go Ahead Eagles,Patrick Maneschijn,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2876,Eredivisie,Go Ahead Eagles,Givan Werkhoven,Forward,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
2877,Eredivisie,Go Ahead Eagles,Erik Cummins,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [54]:
df5=data5[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2487,34.0,4,34.0,2,2,1,1,2,0,0,0,0,0.0,1020.00
2488,34.0,14,31.0,14,0,12,0,1,2,0,11,0,9.0,933.00
2489,33.0,21,33.0,12,9,18,2,1,3,1,16,0,13.0,0.00
2490,32.0,0,32.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2491,31.0,3,29.0,2,1,1,1,1,0,0,1,0,0.0,371.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2873,6.0,0,6.0,0,0,0,0,0,0,0,0,0,0.0,485.00
2874,2.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2875,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2876,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
2877,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [55]:
dfn5=df5.apply(minmax,axis=0)
dfn5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2487,1.000000,0.190476,1.000000,0.142857,0.181818,0.055556,0.076923,0.4,0.0,0.000000,0.0000,0.0,0.000000,0.333333
2488,1.000000,0.666667,0.911765,1.000000,0.000000,0.666667,0.000000,0.2,0.4,0.000000,0.6875,0.0,0.692308,0.304902
2489,0.970588,1.000000,0.970588,0.857143,0.818182,1.000000,0.153846,0.2,0.6,0.166667,1.0000,0.0,1.000000,0.000000
2490,0.941176,0.000000,0.941176,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.000000,0.000000
2491,0.911765,0.142857,0.852941,0.142857,0.090909,0.055556,0.076923,0.2,0.0,0.000000,0.0625,0.0,0.000000,0.121337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2873,0.176471,0.000000,0.176471,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.000000,0.158497
2874,0.058824,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.000000,0.000000
2875,0.029412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.000000,0.000000
2876,0.029412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.000000,0.000000
2877,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.000000,0.000000

In [56]:
dfn_sum5=dfn5.sum(axis=1).sort_values(ascending=False)
dfn_sum5

2689    9.123994
2660    8.827336
2489    8.737014
2579    8.464125
2621    7.409701
          ...
2593    0.000000
2553    0.000000
2552    0.000000
2551    0.000000
2681    0.000000
Length: 374, dtype: float64

In [57]:
data['Player'][2689]

'Samuel Armenteros'

In [58]:
####Serie A######

In [59]:
data6=new_data[new_data['League']=='Serie A']
data6

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
2879,Serie A,Juventus,Simone Zaza,Forward,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2880,Serie A,Juventus,Patrice Evra,Defender,6.0,0,3.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2881,Serie A,Juventus,Gonzalo Higuain,Forward,38.0,24,32.0,0.0,2968.0,13,11,18,5,1,0,22,2,0
2882,Serie A,Juventus,Mario Mandzukic,Forward,35.0,7,29.0,0.0,515.4,5,2,3,2,2,0,4,2,0
2883,Serie A,Juventus,Sami Khedira,Midfielder,31.0,5,31.0,0.0,1274.5,2,3,4,0,1,0,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3626,Serie A,Pescara,Francesco Mele,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3627,Serie A,Pescara,Marco Pompetti,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3628,Serie A,Pescara,Ferdinand Del Sole,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3629,Serie A,Pescara,Marco Acatullo,Forward,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3630,Serie A,Pescara,Gabriele Aldegani,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [60]:
df6=data6[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2879,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2880,6.0,0,3.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2881,38.0,24,32.0,13,11,18,5,1,2,0,22,0,0.0,2968.0
2882,35.0,7,29.0,5,2,3,2,2,2,0,4,0,0.0,515.4
2883,31.0,5,31.0,2,3,4,0,1,1,0,4,0,0.0,1274.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3626,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3627,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3628,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3629,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3630,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [61]:
dfn6=df6.apply(minmax,axis=0)
dfn6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2879,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
2880,0.157895,0.000000,0.078947,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
2881,1.000000,0.827586,0.842105,0.722222,0.733333,0.782609,0.454545,0.1,0.333333,0.0,1.000000,0.0,0.0,0.891291
2882,0.921053,0.241379,0.763158,0.277778,0.133333,0.130435,0.181818,0.2,0.333333,0.0,0.181818,0.0,0.0,0.154775
2883,0.815789,0.172414,0.815789,0.111111,0.200000,0.173913,0.000000,0.1,0.166667,0.0,0.181818,0.0,0.0,0.382733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3626,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
3627,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
3628,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
3629,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
3630,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000

In [62]:
dfn_sum6=dfn6.sum(axis=1).sort_values(ascending=False)
dfn_sum6

3104    9.080098
2960    9.003615
3171    8.788539
2917    8.647829
2881    7.687026
          ...
3233    0.000000
3232    0.000000
3206    0.000000
3205    0.000000
2879    0.000000
Length: 733, dtype: float64

In [63]:
data['Player'][3104]

'Mauro Icardi'

In [64]:
####Scottish Premiership##

In [65]:
data7=new_data[new_data['League']=='Scottish Premiership']
data7

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
3632,Scottish Premiership,Celtic,Moussa Dembele,Forward,29.0,17,20.0,6.0,958.00,9,8,13,3,1,0,11,1,4
3633,Scottish Premiership,Celtic,Craig Gordon,Goalkeeper,35.0,0,34.0,0.0,1034.67,0,0,0,0,0,0,0,0,0
3634,Scottish Premiership,Celtic,Scott Sinclair,Forward,35.0,21,30.0,7.0,1387.50,10,11,16,5,0,0,14,1,5
3635,Scottish Premiership,Celtic,Scott Brown,Midfielder,33.0,1,33.0,0.0,264.91,0,1,0,1,0,0,1,0,0
3636,Scottish Premiership,Celtic,Patrick Roberts,Midfielder,32.0,9,20.0,10.0,1902.00,3,6,2,6,1,0,9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4050,Scottish Premiership,Inverness Cali,Jason Brown,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4051,Scottish Premiership,Inverness Cali,Daniel Hoban,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4052,Scottish Premiership,Inverness Cali,Sam Robertson,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4053,Scottish Premiership,Inverness Cali,Andrew MacRae,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4054,Scottish Premiership,Inverness Cali,Blair MacLennan,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [66]:
df7=data7[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3632,29.0,17,20.0,9,8,13,3,1,1,4,11,0,6.0,958.00
3633,35.0,0,34.0,0,0,0,0,0,0,0,0,0,0.0,1034.67
3634,35.0,21,30.0,10,11,16,5,0,1,5,14,0,7.0,1387.50
3635,33.0,1,33.0,0,1,0,1,0,0,0,1,0,0.0,264.91
3636,32.0,9,20.0,3,6,2,6,1,0,0,9,0,10.0,1902.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4050,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4051,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4052,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4053,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
4054,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [67]:
dfn7=df7.apply(minmax,axis=0)
dfn7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3632,0.763158,0.739130,0.526316,0.5625,0.727273,0.8125,0.3,0.142857,0.333333,0.666667,0.6875,0.0,0.461538,0.283768
3633,0.921053,0.000000,0.894737,0.0000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.306478
3634,0.921053,0.913043,0.789474,0.6250,1.000000,1.0000,0.5,0.000000,0.333333,0.833333,0.8750,0.0,0.538462,0.410989
3635,0.868421,0.043478,0.868421,0.0000,0.090909,0.0000,0.1,0.000000,0.000000,0.000000,0.0625,0.0,0.000000,0.078469
3636,0.842105,0.391304,0.526316,0.1875,0.545455,0.1250,0.6,0.142857,0.000000,0.000000,0.5625,0.0,0.769231,0.563389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4050,0.000000,0.000000,0.000000,0.0000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000
4051,0.000000,0.000000,0.000000,0.0000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000
4052,0.000000,0.000000,0.000000,0.0000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000
4053,0.000000,0.000000,0.000000,0.0000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000
4054,0.000000,0.000000,0.000000,0.0000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000

In [68]:
dfn_sum7=dfn7.sum(axis=1).sort_values(ascending=False)
dfn_sum7

3801    9.236783
3634    8.739687
3637    7.104123
3632    7.006540
3917    6.487853
          ...
3983    0.000000
3982    0.000000
3981    0.000000
3979    0.000000
4054    0.000000
Length: 412, dtype: float64

In [69]:
data['Player'][3801]

'Liam Boyce'