In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("C:/Users/Adith/Desktop/football_analysis/Football/Player Stats 2017-18.csv")

In [3]:
data=data.dropna(subset=['Player'])

In [4]:
data=data.fillna(0)

In [5]:
data=data.replace(to_replace='-',value=0)

In [6]:
data=pd.DataFrame(data)

In [7]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [8]:
new_data=data[['League', 'Team','Player', 'Position','Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,Premier League,Manchester City,Kevin De Bruyne,Midfielder,37.0,8,36.0,5,3,3,5,0,0,0,6,2,16.0,3085
2,Premier League,Manchester City,Ederson,Goalkeeper,36.0,0,36.0,0,0,0,0,0,0,0,0,0,0.0,0
3,Premier League,Manchester City,Bernardo Silva,Midfielder,35.0,6,15.0,4,2,1,5,0,2,0,4,0,0.0,0
4,Premier League,Manchester City,Fernandinho,Midfielder,34.0,5,33.0,3,2,3,2,0,0,0,4,0,0.0,412.14
5,Premier League,Manchester City,Nicolas Otamendi,Defender,34.0,4,33.0,2,2,2,0,2,1,0,1,0,0.0,329.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4181,Scottish Premiership,Ross County,Mark Foden,Goalkeeper,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4182,Scottish Premiership,Ross County,Russell Dingwall,Forward,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4183,Scottish Premiership,Ross County,Tony Dingwall,Midfielder,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4184,Scottish Premiership,Ross County,Ross Munro,Goalkeeper,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
4185,Scottish Premiership,Ross County,Blair Malcolm,Midfielder,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [9]:
new_data.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [10]:
home=new_data['Home'].astype(str).astype(int)
Away=new_data['Away'].astype(str).astype(int)
rft=new_data['Right Foot'].astype(str).astype(int)
lft=new_data['Left Foot'].astype(str).astype(int)
hdr=new_data['Header'].astype(str).astype(int)
dfk=new_data['Direct Free Kick'].astype(str).astype(int)
myc=new_data['Minutes per Yellow Cards'].astype(str).astype(float)
op=new_data['Open Play'].astype(str).astype(int)
cross=new_data['Cross'].astype(str).astype(int)
penalty=new_data['Penalty'].astype(str).astype(int)

In [11]:
new_data = new_data.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [12]:
new_data["Home"]=home
new_data['Away']=Away
new_data['Right Foot']=rft
new_data['Left Foot']=lft
new_data['Header']=hdr
new_data['Direct Free Kick']=dfk
new_data['Minutes per Yellow Cards']=myc
new_data['Open Play']=op
new_data['Cross']=cross
new_data['Penalty']=penalty

In [13]:
new_data

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,Premier League,Manchester City,Kevin De Bruyne,Midfielder,37.0,8,36.0,16.0,3085.00,5,3,3,5,0,2,6,0,0
2,Premier League,Manchester City,Ederson,Goalkeeper,36.0,0,36.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3,Premier League,Manchester City,Bernardo Silva,Midfielder,35.0,6,15.0,0.0,0.00,4,2,1,5,0,0,4,2,0
4,Premier League,Manchester City,Fernandinho,Midfielder,34.0,5,33.0,0.0,412.14,3,2,3,2,0,0,4,0,0
5,Premier League,Manchester City,Nicolas Otamendi,Defender,34.0,4,33.0,0.0,329.78,2,2,2,0,2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4181,Scottish Premiership,Ross County,Mark Foden,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4182,Scottish Premiership,Ross County,Russell Dingwall,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4183,Scottish Premiership,Ross County,Tony Dingwall,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4184,Scottish Premiership,Ross County,Ross Munro,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
4185,Scottish Premiership,Ross County,Blair Malcolm,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [14]:
new_data.isnull().sum()

League                      0
Team                        0
Player                      0
Position                    0
Appearances                 0
Goals                       0
Started                     0
Assists                     0
Minutes per Yellow Cards    0
Home                        0
Away                        0
Right Foot                  0
Left Foot                   0
Header                      0
Direct Free Kick            0
Open Play                   0
Cross                       0
Penalty                     0
dtype: int64

In [15]:
data.columns

Index(['League', 'Team', 'Season', 'KEY', 'Player', 'Position', 'Appearances',
       'Goals', 'Started', 'Started As A Sub', 'Came On', 'Taken Off',
       'Own Goals', 'Type Of Goal', 'First Half', 'Second Half',
       'First Scorer', 'Last Scorer', 'Home', 'Away', 'Right Foot',
       'Left Foot', 'Header', 'Other Method', 'Open Play', 'Cross',
       'Free Kick', 'Direct Free Kick', 'Throw In', 'Penalty', 'Corner',
       'Other Type Of Play', 'Minutes played', 'Min/goal', 'Assists',
       '% Assists', 'Leading Recipient', 'Recipient Goals', 'CS',
       '% Clean Sheets', 'Hat Tricks', 'Yellow Cards', 'Yellow - First Half',
       'Yellow - Second Half', 'Yellow - Home', 'Yellow - Away',
       'Yelow - Minutes Played', 'Minutes per Yellow Cards', 'Sent Off',
       'Straight Red Card', 'Two Yellow Cards', 'Red - First Half',
       'Red - Second Half', 'Red - Home', 'Red - Away', 'Red - Minutes Played',
       'Minutes per Red Cards'],
      dtype='object')

In [16]:
###Premier League##

In [17]:
data1=data[data['League']=='Premier League']
data1

,League,Team,Season,KEY,Player,Position,Appearances,Goals,Started,Started As A Sub,...,Minutes per Yellow Cards,Sent Off,Straight Red Card,Two Yellow Cards,Red - First Half,Red - Second Half,Red - Home,Red - Away,Red - Minutes Played,Minutes per Red Cards
1,Premier League,Manchester City,2017/18,Premier League|Manchester City|2017/18,Kevin De Bruyne,Midfielder,37.0,8,36.0,2.0,...,3085,0.0,0,0,0,0,0,0,0.0,0.0
2,Premier League,Manchester City,2017/18,Premier League|Manchester City|2017/18,Ederson,Goalkeeper,36.0,0,36.0,2.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
3,Premier League,Manchester City,2017/18,Premier League|Manchester City|2017/18,Bernardo Silva,Midfielder,35.0,6,15.0,23.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
4,Premier League,Manchester City,2017/18,Premier League|Manchester City|2017/18,Fernandinho,Midfielder,34.0,5,33.0,1.0,...,412.14,0.0,0,0,0,0,0,0,0.0,0.0
5,Premier League,Manchester City,2017/18,Premier League|Manchester City|2017/18,Nicolas Otamendi,Defender,34.0,4,33.0,2.0,...,329.78,0.0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,Premier League,West Bromwich Albion,2017/18,Premier League|West Bromwich Albion|2017/18,Kane Wilson,Defender,0.0,0,0.0,3.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
619,Premier League,West Bromwich Albion,2017/18,Premier League|West Bromwich Albion|2017/18,Ali Gabr,Defender,0.0,0,0.0,2.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
620,Premier League,West Bromwich Albion,2017/18,Premier League|West Bromwich Albion|2017/18,Rayhaan Tulloch,Forward,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
621,Premier League,West Bromwich Albion,2017/18,Premier League|West Bromwich Albion|2017/18,Max Melbourne,Midfielder,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
622,Premier League,West Bromwich Albion,2017/18,Premier League|West Bromwich Albion|2017/18,Nathan Ferguson,Defender,0.0,0,0.0,1.0,...,0,0.0,0,0,0,0,0,0,0.0,0.0

In [18]:
df1=data1[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df1

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1,37.0,8,36.0,5,3,3,5,0,0,0,6,2,16.0,3085
2,36.0,0,36.0,0,0,0,0,0,0,0,0,0,0.0,0
3,35.0,6,15.0,4,2,1,5,0,2,0,4,0,0.0,0
4,34.0,5,33.0,3,2,3,2,0,0,0,4,0,0.0,412.14
5,34.0,4,33.0,2,2,2,0,2,1,0,1,0,0.0,329.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
619,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
620,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
621,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0
622,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0

In [19]:
df1.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                         object
Away                         object
Right Foot                   object
Left Foot                    object
Header                       object
Cross                        object
Penalty                      object
Open Play                    object
Direct Free Kick             object
Assists                     float64
Minutes per Yellow Cards     object
dtype: object

In [20]:
home=df1['Home'].astype(str).astype(int)
Away=df1['Away'].astype(str).astype(int)
rft=df1['Right Foot'].astype(str).astype(int)
lft=df1['Left Foot'].astype(str).astype(int)
hdr=df1['Header'].astype(str).astype(int)
dfk=df1['Direct Free Kick'].astype(str).astype(int)
myc=df1['Minutes per Yellow Cards'].astype(str).astype(float)
op=df1['Open Play'].astype(str).astype(int)
cross=df1['Cross'].astype(str).astype(int)
penalty=df1['Penalty'].astype(str).astype(int)

In [21]:
df1 = df1.drop(['Home','Away','Right Foot','Left Foot','Header',
         'Direct Free Kick','Open Play','Cross','Penalty'], axis=1)

In [22]:
df1["Home"]=home
df1['Away']=Away
df1['Right Foot']=rft
df1['Left Foot']=lft
df1['Header']=hdr
df1['Direct Free Kick']=dfk
df1['Minutes per Yellow Cards']=myc
df1['Open Play']=op
df1['Cross']=cross
df1['Penalty']=penalty

In [23]:
df1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,37.0,8,36.0,16.0,3085.00,5,3,3,5,0,2,6,0,0
2,36.0,0,36.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3,35.0,6,15.0,0.0,0.00,4,2,1,5,0,0,4,2,0
4,34.0,5,33.0,0.0,412.14,3,2,3,2,0,0,4,0,0
5,34.0,4,33.0,0.0,329.78,2,2,2,0,2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
619,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
620,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
621,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
622,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [24]:
def minmax(col):
    ncol=[]
    mx=col.max()
    mn=col.min()
    for i in col:
        ncol.append((i-mn)/(mx-mn))
    return ncol

In [25]:
dfn1=df1.apply(minmax,axis=0)

In [26]:
dfn1

,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1,0.973684,0.25000,0.947368,1.0,0.902047,0.263158,0.200000,0.200000,0.20,0.000000,1.0,0.214286,0.000000,0.0
2,0.947368,0.00000,0.947368,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.0
3,0.921053,0.18750,0.394737,0.0,0.000000,0.210526,0.133333,0.066667,0.20,0.000000,0.0,0.142857,0.285714,0.0
4,0.894737,0.15625,0.868421,0.0,0.120509,0.157895,0.133333,0.200000,0.08,0.000000,0.0,0.142857,0.000000,0.0
5,0.894737,0.12500,0.868421,0.0,0.096427,0.105263,0.133333,0.133333,0.00,0.285714,0.0,0.035714,0.142857,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.0
619,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.0
620,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.0
621,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.0
622,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.0

In [27]:
dfn_sum1=dfn1.sum(axis=1).sort_values(ascending=False)
dfn_sum1

87     9.378634
55     9.140098
12     7.178288
244    7.025501
86     6.490135
         ...
177    0.000000
468    0.000000
469    0.000000
470    0.000000
622    0.000000
Length: 603, dtype: float64

In [28]:
data1['Player'][87]

'Mohamed Salah'

In [29]:
data['Player'][55]

'Harry Kane'

In [30]:
#####Bundesliga#######

In [30]:
data2=new_data[new_data['League']=='Bundesliga']
data2

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
624,Bundesliga,Bayern Munich,Renato Sanches,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
625,Bundesliga,Bayern Munich,Sven Ulreich,Goalkeeper,30.0,0,30.0,0.0,2700.0,0,0,0,0,0,0,0,0,0
626,Bundesliga,Bayern Munich,Robert Lewandowski,Forward,30.0,29,24.0,0.0,2169.0,21,8,18,6,5,0,16,4,6
627,Bundesliga,Bayern Munich,Joshua Kimmich,Midfielder,29.0,1,26.0,9.0,2332.0,1,0,1,0,0,0,1,0,0
628,Bundesliga,Bayern Munich,Thomas Muller,Forward,29.0,8,22.0,14.0,491.0,5,3,5,3,0,0,7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172,Bundesliga,1. FC Koln,Anas Ouahim,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1173,Bundesliga,1. FC Koln,Filip Kusic,Defender,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1174,Bundesliga,1. FC Koln,Sven Muller,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1175,Bundesliga,1. FC Koln,Thomas Kessler,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1176,Bundesliga,1. FC Koln,Artjoms Rudnevs,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [31]:
data2.dtypes

League                       object
Team                         object
Player                       object
Position                     object
Appearances                 float64
Goals                         int64
Started                     float64
Assists                     float64
Minutes per Yellow Cards    float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Direct Free Kick              int32
Open Play                     int32
Cross                         int32
Penalty                       int32
dtype: object

In [32]:
df2=data2[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
624,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
625,30.0,0,30.0,0,0,0,0,0,0,0,0,0,0.0,2700.0
626,30.0,29,24.0,21,8,18,6,5,4,6,16,0,0.0,2169.0
627,29.0,1,26.0,1,0,1,0,0,0,0,1,0,9.0,2332.0
628,29.0,8,22.0,5,3,5,3,0,0,0,7,0,14.0,491.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1173,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1174,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1175,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1176,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [33]:
df2.dtypes

Appearances                 float64
Goals                         int64
Started                     float64
Home                          int32
Away                          int32
Right Foot                    int32
Left Foot                     int32
Header                        int32
Cross                         int32
Penalty                       int32
Open Play                     int32
Direct Free Kick              int32
Assists                     float64
Minutes per Yellow Cards    float64
dtype: object

In [34]:
dfn2=df2.apply(minmax,axis=0)
dfn2

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
624,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000
625,0.857143,0.000000,0.882353,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.882353
626,0.857143,1.000000,0.705882,1.000000,1.000,1.000000,0.545455,1.0,1.0,1.0,1.0000,0.0,0.000000,0.708824
627,0.828571,0.034483,0.764706,0.047619,0.000,0.055556,0.000000,0.0,0.0,0.0,0.0625,0.0,0.642857,0.762092
628,0.828571,0.275862,0.647059,0.238095,0.375,0.277778,0.272727,0.0,0.0,0.0,0.4375,0.0,1.000000,0.160458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172,0.028571,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000
1173,0.028571,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000
1174,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000
1175,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000
1176,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000

In [35]:
dfn_sum2=dfn2.sum(axis=1).sort_values(ascending=False)
dfn_sum2

626     10.817303
689      7.490831
777      6.685913
984      6.494713
1050     6.340284
          ...
890      0.000000
891      0.000000
1175     0.000000
917      0.000000
624      0.000000
Length: 536, dtype: float64

In [36]:
data['Player'][626]

'Robert Lewandowski'

In [38]:
#####LA liga####

In [39]:
data3=new_data[new_data['League']=='La Liga']
data3

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1178,La Liga,Barcelona,Philippe Coutinho,Midfielder,18.0,8,16.0,0.0,1304.00,3,5,8,0,0,0,8,0,0
1179,La Liga,Barcelona,Gerard Deulofeu,Midfielder,10.0,1,5.0,0.0,503.00,1,0,1,0,0,0,1,0,0
1180,La Liga,Barcelona,Marc Andre ter Stegen,Goalkeeper,37.0,0,37.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1181,La Liga,Barcelona,Lionel Messi,Forward,36.0,34,32.0,12.0,998.67,21,13,2,32,0,6,26,0,2
1182,La Liga,Barcelona,Ivan Rakitic,Midfielder,35.0,1,31.0,0.0,709.50,0,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,La Liga,Malaga,Alberto Lopez,Defender,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1816,La Liga,Malaga,Juan Cruz,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1817,La Liga,Malaga,Jose Carlos Sanchez,Midfielder,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1818,La Liga,Malaga,Cenk Gonen,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
1819,La Liga,Malaga,Ian Pino,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [40]:
df3=data3[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1178,18.0,8,16.0,3,5,8,0,0,0,0,8,0,0.0,1304.00
1179,10.0,1,5.0,1,0,1,0,0,0,0,1,0,0.0,503.00
1180,37.0,0,37.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1181,36.0,34,32.0,21,13,2,32,0,0,2,26,6,12.0,998.67
1182,35.0,1,31.0,0,1,0,1,0,0,0,1,0,0.0,709.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1816,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1817,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1818,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
1819,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [41]:
dfn3=df3.apply(minmax,axis=0)
dfn3

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1178,0.473684,0.235294,0.421053,0.142857,0.357143,0.421053,0.00000,0.0,0.0,0.000000,0.307692,0.0,0.0,0.391592
1179,0.263158,0.029412,0.131579,0.047619,0.000000,0.052632,0.00000,0.0,0.0,0.000000,0.038462,0.0,0.0,0.151051
1180,0.973684,0.000000,0.973684,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
1181,0.947368,1.000000,0.842105,1.000000,0.928571,0.105263,1.00000,0.0,0.0,0.333333,1.000000,1.0,1.0,0.299901
1182,0.921053,0.029412,0.815789,0.000000,0.071429,0.000000,0.03125,0.0,0.0,0.000000,0.038462,0.0,0.0,0.213063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
1816,0.026316,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
1817,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
1818,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
1819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000

In [42]:
dfn_sum3=dfn3.sum(axis=1).sort_values(ascending=False)
dfn_sum3

1181    9.456543
1184    8.173510
1249    7.631507
1472    6.933010
1528    6.360359
          ...
1561    0.000000
1578    0.000000
1579    0.000000
1297    0.000000
1819    0.000000
Length: 623, dtype: float64

In [44]:
data['Player'][1181]

'Lionel Messi'

In [45]:
####French Ligue 1####

In [46]:
data4=new_data[new_data['League']=='French Ligue 1']
data4

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
1821,French Ligue 1,Paris Saint-Germain,Lucas Moura,Midfielder,5.0,1,0.0,0.0,71.0,0,1,0,1,0,0,1,0,0
1822,French Ligue 1,Paris Saint-Germain,Goncalo Guedes,Forward,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1823,French Ligue 1,Paris Saint-Germain,Alphonse Areola,Goalkeeper,34.0,0,34.0,0.0,0.0,0,0,0,0,0,0,0,0,0
1824,French Ligue 1,Paris Saint-Germain,Adrien Rabiot,Midfielder,33.0,1,27.0,0.0,1183.0,1,0,0,1,0,0,1,0,0
1825,French Ligue 1,Paris Saint-Germain,Giovani Lo Celso,Midfielder,33.0,4,18.0,0.0,884.0,2,2,0,3,1,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,French Ligue 1,FC Metz,Lilian Fournier,Midfielder,1.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2466,French Ligue 1,FC Metz,Youssef Maziz,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2467,French Ligue 1,FC Metz,Vincent Peugnet,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2468,French Ligue 1,FC Metz,Bilal Hadraoui,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
2469,French Ligue 1,FC Metz,Theodore Efouba Ayissi,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [47]:
df4=data4[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1821,5.0,1,0.0,0,1,0,1,0,0,0,1,0,0.0,71.0
1822,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1823,34.0,0,34.0,0,0,0,0,0,0,0,0,0,0.0,0.0
1824,33.0,1,27.0,1,0,0,1,0,0,0,1,0,0.0,1183.0
1825,33.0,4,18.0,2,2,0,3,1,1,0,2,0,0.0,884.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2466,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2467,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2468,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
2469,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [48]:
dfn4=df4.apply(minmax,axis=0)
dfn4

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
1821,0.131579,0.035714,0.000000,0.000000,0.090909,0.0,0.0625,0.000,0.000,0.0,0.055556,0.0,0.0,0.020760
1822,0.026316,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000
1823,0.894737,0.000000,0.894737,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000
1824,0.868421,0.035714,0.710526,0.052632,0.000000,0.0,0.0625,0.000,0.000,0.0,0.055556,0.0,0.0,0.345906
1825,0.868421,0.142857,0.473684,0.105263,0.181818,0.0,0.1875,0.125,0.125,0.0,0.111111,0.0,0.0,0.258480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,0.026316,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000
2466,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000
2467,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000
2468,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000
2469,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0000,0.000,0.000,0.0,0.000000,0.0,0.0,0.000000

In [49]:
dfn_sum4=dfn4.sum(axis=1).sort_values(ascending=False)
dfn_sum4

1826    9.309472
1922    8.645661
1894    7.879480
1838    7.614251
1900    7.314177
          ...
2148    0.000000
2147    0.000000
2146    0.000000
2145    0.000000
2469    0.000000
Length: 630, dtype: float64

In [51]:
data['Player'][1826]

'Edinson Cavani'

In [52]:
####Eredivisie###

In [53]:
data5=new_data[new_data['League']=='Eredivisie']
data5

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
2471,Eredivisie,PSV Eindhoven,Jurgen Locadia,Forward,15.0,9,15.0,0.0,1253.00,2,7,7,2,0,0,8,0,1
2472,Eredivisie,PSV Eindhoven,Jorrit Hendrix,Midfielder,33.0,2,33.0,0.0,402.57,0,2,0,2,0,0,2,0,0
2473,Eredivisie,PSV Eindhoven,Joshua Brenet,Defender,32.0,1,32.0,0.0,1411.00,1,0,1,0,0,0,1,0,0
2474,Eredivisie,PSV Eindhoven,Nicolas Isimat-Mirin,Defender,32.0,1,32.0,0.0,719.25,0,1,0,1,0,0,1,0,0
2475,Eredivisie,PSV Eindhoven,Jeroen Zoet,Goalkeeper,32.0,0,32.0,0.0,2879.00,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3048,Eredivisie,FC Twente,Ryan Trotman,Forward,1.0,0,1.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3049,Eredivisie,FC Twente,Rashaan Fernandes,Midfielder,1.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3050,Eredivisie,FC Twente,David Sambissa,Defender,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3051,Eredivisie,FC Twente,Nick Hengelman,Goalkeeper,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0
3052,Eredivisie,FC Twente,Jonatan Frimann,Forward,0.0,0,0.0,0.0,0.00,0,0,0,0,0,0,0,0,0

In [54]:
df5=data5[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2471,15.0,9,15.0,2,7,7,2,0,0,1,8,0,0.0,1253.00
2472,33.0,2,33.0,0,2,0,2,0,0,0,2,0,0.0,402.57
2473,32.0,1,32.0,1,0,1,0,0,0,0,1,0,0.0,1411.00
2474,32.0,1,32.0,0,1,0,1,0,0,0,1,0,0.0,719.25
2475,32.0,0,32.0,0,0,0,0,0,0,0,0,0,0.0,2879.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3048,1.0,0,1.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3049,1.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3050,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3051,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00
3052,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.00

In [55]:
dfn5=df5.apply(minmax,axis=0)
dfn5

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
2471,0.441176,0.428571,0.441176,0.166667,0.777778,0.4375,0.142857,0.0,0.0,0.111111,0.533333,0.0,0.0,0.409477
2472,0.970588,0.095238,0.970588,0.000000,0.222222,0.0000,0.142857,0.0,0.0,0.000000,0.133333,0.0,0.0,0.131559
2473,0.941176,0.047619,0.941176,0.083333,0.000000,0.0625,0.000000,0.0,0.0,0.000000,0.066667,0.0,0.0,0.461111
2474,0.941176,0.047619,0.941176,0.000000,0.111111,0.0000,0.071429,0.0,0.0,0.000000,0.066667,0.0,0.0,0.235049
2475,0.941176,0.000000,0.941176,0.000000,0.000000,0.0000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.940850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3048,0.029412,0.000000,0.029412,0.000000,0.000000,0.0000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
3049,0.029412,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
3050,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
3051,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000
3052,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000

In [56]:
dfn_sum5=dfn5.sum(axis=1).sort_values(ascending=False)
dfn_sum5

2536    9.085466
2568    8.423576
2539    8.343210
2480    7.773634
2659    7.701304
          ...
2912    0.000000
2913    0.000000
2809    0.000000
2808    0.000000
3052    0.000000
Length: 565, dtype: float64

In [57]:
data['Player'][2536]

'Alireza Jahanbakhsh'

In [58]:
####Serie A######

In [59]:
data6=new_data[new_data['League']=='Serie A']
data6

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
3054,Serie A,Juventus,Marko Pjaca,Forward,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3055,Serie A,Juventus,Benedikt Howedes,Defender,3.0,1,3.0,0.0,248.0,1,0,0,0,1,0,0,1,0
3056,Serie A,Juventus,Blaise Matuidi,Midfielder,31.0,3,26.0,0.0,755.0,1,2,0,3,0,0,3,0,0
3057,Serie A,Juventus,Gonzalo Higuain,Forward,35.0,16,32.0,6.0,704.5,8,8,9,5,2,0,12,1,1
3058,Serie A,Juventus,Paulo Dybala,Forward,33.0,22,26.0,0.0,0.0,9,13,4,18,0,3,16,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3759,Serie A,Benevento,Alessio Donnarumma,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3760,Serie A,Benevento,Michele Camporese,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3761,Serie A,Benevento,Thomas Candeloro,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3762,Serie A,Benevento,Riccardo Piscitelli,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3763,Serie A,Benevento,Vincenzo Pinto,Forward,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [60]:
df6=data6[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3054,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3055,3.0,1,3.0,1,0,0,0,1,1,0,0,0,0.0,248.0
3056,31.0,3,26.0,1,2,0,3,0,0,0,3,0,0.0,755.0
3057,35.0,16,32.0,8,8,9,5,2,1,1,12,0,6.0,704.5
3058,33.0,22,26.0,9,13,4,18,0,0,3,16,3,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3759,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3760,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3761,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3762,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3763,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [61]:
dfn6=df6.apply(minmax,axis=0)
dfn6

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3054,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3055,0.076923,0.034483,0.078947,0.0625,0.0000,0.000000,0.000000,0.111111,0.166667,0.000000,0.000000,0.0,0.000000,0.074474
3056,0.794872,0.103448,0.684211,0.0625,0.1250,0.000000,0.166667,0.000000,0.000000,0.000000,0.166667,0.0,0.000000,0.226727
3057,0.897436,0.551724,0.842105,0.5000,0.5000,0.409091,0.277778,0.222222,0.166667,0.142857,0.666667,0.0,0.428571,0.211562
3058,0.846154,0.758621,0.684211,0.5625,0.8125,0.181818,1.000000,0.000000,0.000000,0.428571,0.888889,1.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3759,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3760,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3761,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3762,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3763,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000

In [62]:
dfn_sum6=dfn6.sum(axis=1).sort_values(ascending=False)
dfn_sum6

3191    9.469572
3155    9.439803
3058    7.163264
3360    7.087608
3088    6.852872
          ...
3345    0.000000
3344    0.000000
3318    0.000000
3314    0.000000
3054    0.000000
Length: 691, dtype: float64

In [65]:
data['Player'][3191]

'Mauro Icardi'

In [66]:
####Scottish Premiership##

In [67]:
data7=new_data[new_data['League']=='Scottish Premiership']
data7

,League,Team,Player,Position,Appearances,Goals,Started,Assists,Minutes per Yellow Cards,Home,Away,Right Foot,Left Foot,Header,Direct Free Kick,Open Play,Cross,Penalty
3765,Scottish Premiership,Celtic,Moussa Dembele,Forward,25.0,9,17.0,6.0,723.5,3,6,8,0,1,0,6,2,1
3766,Scottish Premiership,Celtic,Charly Musonda,Midfielder,4.0,0,2.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3767,Scottish Premiership,Celtic,Marvin Compper,Defender,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
3768,Scottish Premiership,Celtic,Callum McGregor,Midfielder,36.0,7,29.0,0.0,1319.0,5,2,3,4,0,0,7,0,0
3769,Scottish Premiership,Celtic,James Forrest,Forward,35.0,8,31.0,7.0,2528.0,6,2,4,4,0,0,8,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4181,Scottish Premiership,Ross County,Mark Foden,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4182,Scottish Premiership,Ross County,Russell Dingwall,Forward,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4183,Scottish Premiership,Ross County,Tony Dingwall,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4184,Scottish Premiership,Ross County,Ross Munro,Goalkeeper,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0
4185,Scottish Premiership,Ross County,Blair Malcolm,Midfielder,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0

In [68]:
df7=data7[['Appearances','Goals',
        'Started','Home','Away','Right Foot','Left Foot','Header','Cross','Penalty','Open Play',
         'Direct Free Kick','Assists','Minutes per Yellow Cards']]
df7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3765,25.0,9,17.0,3,6,8,0,1,2,1,6,0,6.0,723.5
3766,4.0,0,2.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3767,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
3768,36.0,7,29.0,5,2,3,4,0,0,0,7,0,0.0,1319.0
3769,35.0,8,31.0,6,2,4,4,0,0,0,8,0,7.0,2528.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4181,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
4182,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
4183,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
4184,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0
4185,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [69]:
dfn7=df7.apply(minmax,axis=0)
dfn7

,Appearances,Goals,Started,Home,Away,Right Foot,Left Foot,Header,Cross,Penalty,Open Play,Direct Free Kick,Assists,Minutes per Yellow Cards
3765,0.657895,0.500000,0.447368,0.333333,0.6,0.666667,0.000000,0.2,1.0,0.166667,0.428571,0.0,0.750,0.242460
3766,0.105263,0.000000,0.052632,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000
3767,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000
3768,0.947368,0.388889,0.763158,0.555556,0.2,0.250000,0.666667,0.0,0.0,0.000000,0.500000,0.0,0.000,0.442024
3769,0.921053,0.444444,0.815789,0.666667,0.2,0.333333,0.666667,0.0,0.0,0.000000,0.571429,0.0,0.875,0.847185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4181,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000
4182,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000
4183,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000
4184,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000
4185,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000,0.000000

In [70]:
dfn_sum7=dfn7.sum(axis=1).sort_values(ascending=False)
dfn_sum7

3899    9.435627
3833    7.282061
3835    7.132300
4085    6.579090
3933    6.568896
          ...
3973    0.000000
4184    0.000000
4006    0.000000
4007    0.000000
3974    0.000000
Length: 410, dtype: float64

In [71]:
data['Player'][3899]

'Kris Boyd'